IgniteUI/igniteui-docfx

- templates/ignite-ui-template/styles/stackblitz-handler.js
Closes #168.
This PR will break the following functionality: loading stackblitz demos locally will have assets resources not loading because of the HTTP protocol we use in development environment.
> Added assets demo url based on environment

- en/components/tabbar.md
- en/components/toc.yml
Deprecate tabbar's selector igx-tab-bar. Introduce new selector named igx-bottom-nav.
IgniteUI/igniteui-angular#954.
> Deprecate tabbar's selector `igx-tab-bar`

- templates/ignite-ui-template/styles/docfx.js
- web.config
Closes #271.
Regarding the issue with StackBlitz not opening from IE 11 (we experience this in IE 11 on prod on all samples):
I am not able to reproduce it on staging, no clue why.
I am reproducing it locally if igniteui-samples and igniteui-docfx have different domains. The issue appears to be that we are getting content from samples (.json files) via AJAX and sending the same content to a third-party (StackBlitz) - this is detected as a XSS from IE 11.
Anyway, disabling XSS via X-XSS-Protection header is the proposed solution all over the net so we can go with it if you decide.
If you need, please perform further tests.
> IE 11 left menu missing and SB samples not opening

- IgniteUIDocFX.nuspec
Renaming the nugget package for octopus deployment to IgniteUIDocFX
> Update and rename angularSampes.nuspec to IgniteUIDocFX.nuspec

- jp/components/chip.md
- jp/components/combo.md
- jp/components/overlay_main.md
- jp/components/toc.yml
Added some backticks for code words.  Fixed spelling.  Untranslated the topic name because it is a control name and we leave those in English.
> Edits for Chip topic and TOC

- package-lock.json
- package.json
We are downgrading `browser-sync`. I hope this is going to be a temporary fix. Related to #672.
> Downgrading browser-sync npm package because of infinite reloading

- en/components/grid_editing.md
- en/components/grid_multi_column_headers.md
- en/components/grid_paging.md
- en/components/grid_selection.md
- en/components/grid_sorting.md
- en/components/grid_summaries.md
- en/components/grid_virtualization.md
- jp/components/grid_editing.md
- jp/components/grid_multi_column_headers.md
- jp/components/grid_paging.md
- jp/components/grid_selection.md
- jp/components/grid_sorting.md
- jp/components/grid_summaries.md
- jp/components/grid_virtualization.md
Closes #729 
Configuring Typedoc and Sassdoc references for topics:
-   Grid Virtualization
-   Grid Editing
-   Grid Sorting
-   Grid Summaries
-   Grid Paging
-   Grid Selection
-   Grid Display Density
> Configuring Typedoc and Sassdoc references in topics.

- en/components/grids_and_lists.md
- jp/components/grids_and_lists.md
- kr/components/grids_and_lists.md
I had to make some minor updates for SEO purposes. EN is ready to go, but there two minor changes that need to be updated for JP and KR sites. 
@yoshimis I already applied one of the changes by switch the h2 to an h1, but we also added the word "virtualized" in the opening paragraph. The additional change of adding a link on the Virtualization and Performance description isn't applicable to JP and KR websites, so that could be skipped.
@pamelabrasil, @zdrawku and @tiliev please let me know if you have any questions regarding this. These changes can go live anytime your ready.
> Added some recommended SEO improvements

- jp/components/toc.yml
JP TOC has an issue with expanding Excel Library:
> Fixed JP TOC

- en/components/calendar.md
- en/components/date_picker.md
- en/components/time_picker.md
- jp/components/calendar.md
- jp/components/date_picker.md
- jp/components/time_picker.md
- kr/components/calendar.md
- kr/components/date_picker.md
- kr/components/time_picker.md
Related to #921 
For the following components:
- Calendar
- DatePicker
- TimePicker
please test whether the samples in the corresponding topics open and whether the same samples work in StackBlitz.
> correct the url to scheduling samples due to the new scheduling bundle

- en/components/navbar.md
- en/components/navdrawer.md
- jp/components/navbar.md
- jp/components/navdrawer.md
- kr/components/navbar.md
- kr/components/navdrawer.md
Related to #921
For the following components:
-  Navbar
-  Navdrawer
> correct the url to menus samples due to the new menus bundle

- jp/components/overlay_position.md
Noticed that the Elastic table [here](https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/overlay_position.html) is badly formatted possibly due to a missing space which I added.
> Adding a space in order to try to fix the table.

- en/components/themes/examples.md
- jp/components/themes/examples.md
- kr/components/themes/examples.md
- kr/components/themes/theming-demo.md
Code examples had some double slashes in import paths.
> docs(theming): Fixing import paths for styles

- en/components/button.md
- en/components/input_group.md
- en/components/localization.md
- jp/components/localization.md
- kr/components/localization.md
- package-lock.json
- package.json
> Added lazy loading for iframes

- gulpfile.js
Closes #1008 
Issue was caused by the fact that whenever a template is saved, the watch triggers not only because of it, but also because of the topics that are generated by the template. These generated topics trigger the build task, which on the other hand triggers the **generate-grid-topics** task, which leads to flooding and error.
Currently we exclude all auto-generated topics and include manually in the **gulpfile.js** only the grid specific topics, for which the watch should be working.
> Exclude auto-generated topics from watch

- en/components/combo_templates.md
- en/components/datachart_axis_locations.md
- en/global.json
- jp/components/combo_templates.md
- jp/global.json
- kr/components/combo_templates.md
- kr/global.json
As we’re preparing for a release of the Ignite UI for Angular product on 28 February(see Roadmap doc) I created a 7.1.x branch in the igniteui-angular-samples repo. The master branch now uses igniteui-angular@7.2.0-beta.3 version.
For any emergency fixes to the samples that need to be deployed to production before this date, please use the 7.1.x branch. 
Related PR - https://github.com/IgniteUI/igniteui-angular-samples/pull/979
> Even 7.1.x and master

- en/components/navdrawer.md
- en/components/toggle.md
In `IgxToggle` and `IgxNavigationDrawer` samples we were used deprecated property `closeOnOutsideClick`. This property is removed now from all samples.
Closes #1063
> Remove closeOnOutsideClick from samples

- en/components/grids_templates/batch_editing.md
Closes #1094 
Removing link to `IgxHierarchicalTransactionServiceFactory` and modifying API References section.
After discussion with Stamen we decided to remove the hyperlink to IgxHierarchicalTransactionServiceFactory since it is not generated correctly and leads to 404. Additionally,  the IgxHierarchicalTransactionServiceFactory is removed from the API References section. In this section the same API references as the one for the igxGrid are listed for igxHGrid.
> Removing the link to `IgxHierarchicalTransactionServiceFactory`

- en/components/combo_features.md
- en/components/expansion_panel.md
- jp/components/combo_features.md
- jp/components/expansion_panel.md
- kr/components/combo_features.md
- kr/components/expansion_panel.md
In a component's topic, when mentioning another component, there should be a link that leads to the mentioned component's topic.
> docs(*): update mention of other components in combo and expansion panel

- en/components/general/getting_started.md
- en/components/grids_templates/batch_editing.md
- en/components/grids_templates/column_hiding.md
- en/components/grids_templates/export_excel.md
- en/components/grids_templates/search.md
- en/components/treegrid/tree_grid.md
- jp/components/general/getting_started.md
- jp/components/grids_templates/batch_editing.md
- jp/components/grids_templates/column_hiding.md
- jp/components/grids_templates/export_excel.md
- jp/components/grids_templates/search.md
- jp/components/treegrid/tree_grid.md
- kr/components/general/getting_started.md
- kr/components/grids_templates/batch_editing.md
- kr/components/grids_templates/column_hiding.md
- kr/components/grids_templates/export_excel.md
- kr/components/grids_templates/search.md
- kr/components/treegrid/tree_grid.md
Some API links were decorated with ``, but in most of the topics we don't use it for API links in the "API References" section
> Changing the  styling of links in the API links section

- en/components/avatar.md
- en/components/card.md
- en/components/carousel.md
- en/components/expansion_panel.md
- en/components/tabbar.md
- en/components/tabs.md
- jp/components/avatar.md
- jp/components/card.md
- jp/components/carousel.md
- jp/components/expansion_panel.md
- jp/components/tabbar.md
- jp/components/tabs.md
- kr/components/avatar.md
- kr/components/card.md
- kr/components/carousel.md
- kr/components/expansion_panel.md
- kr/components/tabbar.md
- kr/components/tabs.md
> Add lazyload in Layouts topics for all versions

- en/components/dialog.md
- en/components/overlay_main.md
- en/components/ripple.md
- en/components/slider.md
- en/components/toggle.md
- en/components/tooltip.md
- jp/components/dialog.md
- jp/components/overlay_main.md
- jp/components/ripple.md
- jp/components/slider.md
- jp/components/toggle.md
- jp/components/tooltip.md
- kr/components/dialog.md
- kr/components/overlay_main.md
- kr/components/ripple.md
- kr/components/slider.md
- kr/components/toggle.md
- kr/components/tooltip.md
> Add lazyload in Interaction topics for all versions

- package-lock.json
- package.json
This version contain fixes:
- StackBlitz live editing usage under EDGE https://github.com/IgniteUI/igniteui-docfx-template/issues/94
- Theme changing logic in EDGE and IE11 https://github.com/IgniteUI/igniteui-docfx-template/issues/92
It should be tested for both issues before merging.
> Updating to 2.0.16 version of docfx-template

- en/components/grids_templates/column_resizing.md
- jp/components/grids_templates/column_resizing.md
Removed the note about 88px column resizing limitation
> docs(grid): Update in grid column resizing topic #

- en/components/general/update_guide.md
Adding a note taht if you use the `paginationTemplate` option of `IgxGrid`, `IgxHierarchicalGrid` or `IgxTreeGrid`, you should modify your css to display the pagination correctly.
> Adding a note about updating `paginationTemplate`

- en/components/toast.md
- jp/components/toast.md
> Add toast style docs

- en/components/overlay_position.md
The direction and start point in `Creating position strategy with predefined position settings` sections are different in text description and in the code. This changes the description to match what is in the code
> Fix minor issues in the new overlay position docs

- en/components/tabbar.md
- jp/components/tabbar.md
> Add bottomNav style docs - vNext

- en/components/grids_templates/column_resizing.md
- kr/components/grids_templates/column_resizing.md
> Add information regarding resizing columns in percentages and remove obsolete one.

- en/components/overlay_main.md
- en/components/toggle.md
- jp/components/overlay_main.md
- kr/components/overlay_main.md
Related to https://github.com/IgniteUI/igniteui-angular/issues/7697
<br />
<br />
<br />
> Overlay - closeOnEsc docs

- package-lock.json
- package.json
Update docfx-template to 2.7.6 in order to disable the non-working StackBlitz buttons
> Update to 2.7.6

- en/components/date-picker.md
There is a DV component with the same name 'date-picker' which has overwritten the topic. 
https://github.com/IgniteUI/igniteui-docfx/commits/vNext/en/components/date-picker.md
I'm reverting the original topic. @HUSSAR-mtrela can you create a topic with a different name?
> chore(date-picker): revert date-picker topic

- en/components/general/update-guide.md
Updating the `update-guide` to include a section about `IgxInputGroupComponent.disabled` manual migration.
Related to https://github.com/IgniteUI/igniteui-angular/issues/9339
<br />
<br />
<br />
> feat(update-guide): add section for input-group disabled property

- en/components/date-time-editor.md
Closes #3740 
Note: Тhe [table](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/typography#overview) in typographers topic is actually displayed correctly. A fix was needed only for the [table](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-time-editor#display-and-input-format) in the date-time-editor topic.
<br />
<br />
<br />
> fix(date-time-editor): displaying the table properly

- en/components/general/update-guide.md
Add notes in update guide about breaking changes in combo and simple combo.
Closes #3972 
<br />
<br />
<br />
> docs: Update guide additional steps for 16.1.x to 17.0.x

- en/components/general/angular-grid-overview-guide.md
- jp/components/general/angular-grid-overview-guide.md
- kr/components/themes/global-theme.md
Closes #3843
<br />
<br />
<br />
> chore(*): Update themes import references

- en/components/query-builder.md
- en/components/toc.yml
Reverts IgniteUI/igniteui-docfx#5952
> Revert "docs(query-builder): update topic with nested queries and templating"

- en/components/carousel.md
Closes #5981  
<br />
<br />
<br />
> docs(carousel): update topic with new properties

- jp/components/chip.md
- jp/components/general/data-analysis.md
- jp/components/general/how-to/how-to-use-standalone-components.md
- jp/components/general/ssr-rendering.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> [JA] SSR Rendering topic update, other fixes

- jp/components/charts/features/chart-data-selection.md
- jp/components/general-changelog-dv.md
- jp/components/list.md
- jp/components/menus/toolbar.md
- jp/components/query-builder.md
- jp/components/themes/palettes.md
Closes # 
<br />
<br />
<br />
> JA - List topic, other updates to match EN

- en/components/grids_templates/state-persistence.md
Related to note from https://github.com/IgniteUI/igniteui-angular/pull/14926#issuecomment-2428514259
<br />
<br />
<br />
> Add note regarding persisting requirement for row selection.

- en/components/action-strip.md
All the snippets already weren't setting `hidden=true`, even though the samples code did, so those match the new behavior 😆 
<br />
<br />
<br />
> docs(action-strip): update note with v20 change
