- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update docfx template version to 2.7.2

- en/components/combo_features.md
Closes #2053 
Related: https://github.com/IgniteUI/igniteui-angular/issues/7225
<br />
<br />
<br />
> Add combo default auto strategy note

- en/components/localization.md
> fix: add spanish resource in the documentation #2042

- en/components/general/accessibility-compliance.md
- en/components/toc.yml
Closes #2043
<br />
<br />
<br />
> Add Accessibility compliance vnext

- en/components/general/accessibility-compliance.md
- en/components/toc.yml
Related to #2043
<br />
<br />
<br />
> A11y topic master

- jp/components/grids_templates/column_resizing.md
Closes # 
<br />
<br />
<br />
> adding JP changes from #2045

- en/components/snackbar.md
- en/components/toast.md
Closes #2048 
<br />
<br />
<br />
> IgxSnackbar and IgxToast topic update 

- en/components/snackbar.md
- en/components/toast.md
Closes #2048 
<br />
<br />
<br />
> IgxSnackbar and IgxToast topic update - master

- en/components/grids_templates/state_persistence.md
- en/components/toc.yml
- jp/components/grids_templates/state_persistence.md
- jp/components/toc.yml
Closes #2021
<br />
<br />
<br />
> Update state persistence topic vNext

- en/components/themes/global-theme.md
- en/components/themes/themes-list/bootstrap.md
- en/components/themes/themes-list/fluent.md
- en/components/themes/themes-list/indigo.md
- en/components/toc.yml
> docs(indigo-theme): add topic for indigo theme

- en/components/grids_templates/live_data.md
- jp/components/grids_templates/live_data.md
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/2112
> Change data-demos-base-url on TreeGrid Finjs sample (vnext)

- en/components/grids_templates/live_data.md
- jp/components/grids_templates/live_data.md
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/2112
> Change data-demos-base-url on treegridfinjs (master)

- en/components/grids_templates/summaries.md
- jp/components/grids_templates/summaries.md
Closes # 
<br />
<br />
<br />
> Extend summary topic to describe `showSummaryOnCollapse` property

- en/components/time_picker.md
This PR is related to [Define different styling for hours/minutes outside min and max values](https://github.com/IgniteUI/trial-watermark/issues/32)
<br />
<br />
<br />
> Adding a few words about the disabled time parts functionality in the time picker.

- en/components/navbar.md
Closes #2082
<br />
<br />
<br />
> docs(navbar): Navbar custom title #2082

- en/components/calendar.md
- jp/components/calendar.md
- kr/components/calendar.md
Closes #2080 
<br />
<br />
<br />
> Calendar update topic with new events

- en/components/navbar.md
Closes #2082 
<br />
<br />
<br />
> docs(navbar): Removing text from title #2082

- en/components/exporter_excel.md
- en/components/grids_templates/export_excel.md
Closes #2090
<br />
<br />
<br />
> docs(exporter): add note for JSZip performance issue workaround

- en/components/combo_features.md
Updated the combo filtering section with the case-sensitive search option. 
<br />
<br />
<br />
> Uppdate combo filtering section with case-sensitive option

- en/components/toc.yml
- kr/components/toc.yml
Closes #2108 
<br />
<br />
<br />
> docs(menu): fix spelling error in menu

- en/components/themes/typography.md
Closes #1795 
<br />
<br />
<br />
> docs(typography): remove depricated property

- en/components/grids_templates/paging.md
- en/components/grids_templates/remote_data_operations.md
- jp/components/grids_templates/paging.md
- jp/components/grids_templates/remote_data_operations.md
Closes #2055
Demo update - https://github.com/IgniteUI/igniteui-angular-samples/pull/2146
<br />
<br />
<br />
> Add localization paging section

- en/components/grids_templates/paging.md
- en/components/grids_templates/remote_data_operations.md
- jp/components/grids_templates/paging.md
- jp/components/grids_templates/remote_data_operations.md
Closes #2055
Demo update - IgniteUI/igniteui-angular-samples#2146
> Add paging localization master

- en/components/grids_templates/sorting.md
- en/components/toc.yml
> Add sorting inidicators section in all grid sorting topics

- en/components/overlay_styling.md
> update the overlay_styling.md

- en/components/grid/groupby.md
Closes # 
<br />
<br />
<br />
> chore(*): Add section for custom group by.

- jp/components/calendar.md
- jp/components/exporter_excel.md
- jp/components/grids_templates/export_excel.md
- jp/components/grids_templates/paging.md
- jp/components/themes/typography.md
> Adding changes from #2122, #2120, #2087

- en/components/grids_templates/excel_style_filtering.md
Closes #2104
<br />
<br />
<br />
> Add section for external outlet

- en/components/grids_templates/editing.md
- en/components/grids_templates/row_editing.md
Closes #2137 
<br />
<br />
<br />
> Add the new cellEditDone & rowEditDone events

- en/components/general/getting_started.md
- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update docfx-template version to 2.7.3

- en/components/grids_templates/row_drag.md
Closes #2098 
<br />
<br />
<br />
> fix(grid): move row reorder under Application Demo section - vNext

- en/components/grids_templates/row_drag.md
Closes #2098 
<br />
<br />
<br />
> fix(grid): move row reorder under Application Demo section, #2098

- en/components/general/getting_started.md
- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update template to 2.7.3

- en/components/date_range_picker.md
Closes #2136
<br />
<br />
<br />
> Fix igxDateRangeSeparator typo & link

- en/components/localization.md
- jp/components/localization.md
- kr/components/localization.md
Closes #2149
<br />
<br />
<br />
> Fix korean topic - localization topic 

- en/components/grids_templates/export_excel.md
Closes #2091 
<br />
<br />
<br />
> docs(export-excel): remove obsolete sentence

- en/components/select.md
- en/components/switch.md
- jp/components/select.md
- jp/components/switch.md
> Fix CSB buttons for select and switch topics

- en/components/grids_templates/state_persistence.md
Closes # 
<br />
<br />
<br />
> Update heights on state sample

- en/components/grids_templates/state_persistence.md
> Update heights on state samples

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Upgrade to docfx-tempalte 2.7.4

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update docfx-template to 2.7.5

- jp/components/date_range_picker.md
- jp/components/general/update_guide.md
- jp/components/grids_templates/batch_editing.md
- jp/components/grids_templates/column_hiding.md
- jp/components/grids_templates/excel_style_filtering.md
- jp/components/grids_templates/export_excel.md
- jp/components/grids_templates/keyboard_navigation.md
- jp/components/grids_templates/row_drag.md
- jp/components/grids_templates/row_selection.md
- jp/components/toc.yml
>  [JP] Updating topics to match the latest EN changes. - master

- en/components/input_group.md
Closes # 
<br />
<br />
<br />
> refactor(input-group): update the types section

- jp/components/general/framework-and-features/framework-and-features.md
- jp/components/grid/grid.md
- jp/components/grids_templates/paging.md
- jp/components/ripple.md
Fixes to the codesandbox/stackblitz button order. 
Localization fixes.
> [JP] Localization fixes - vNext

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update to 2.7.6

- en/components/grids_templates/filtering.md
Closes #1880 
<br />
<br />
<br />
> docs(filtering): add known limitations section

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> chore(*): Update docfx-template to 2.7.7

- en/components/combo.md
- en/components/combo_cascading.md
- en/components/combo_features.md
- en/components/combo_remote.md
- en/components/combo_templates.md
Related Issues: #1609, IgniteUI/igniteui-angular-samples/issues/2223
<br />
<br />
<br />
> docs(combo): improve combo component documentation

- en/components/grids_templates/toolbar.md
- en/components/toc.yml
Reverts IgniteUI/igniteui-docfx#2205
> Revert "docs(grid): Toolbar topic add export visaulization"

- en/components/grids_templates/toolbar.md
- en/components/toc.yml
Closes #2187
Reverts IgniteUI/igniteui-docfx#2218
> Re-apply "docs(grid): Toolbar topic add export visualization"

- en/components/grids_templates/column_moving.md
- en/components/toc.yml
- jp/components/grids_templates/column_moving.md
- jp/components/toc.yml
- kr/components/grids_templates/column_moving.md
Closes #2208
<br />
<br />
<br />
> Update column moving topic

- en/components/grids_templates/column_moving.md
Closes # 
<br />
<br />
<br />
> Update missing api link

- en/components/general/angular-grid-overview-guide.md
- en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
- en/components/grid/grid.md
- en/components/list.md
Closes #2228
Closes #2216 
<br />
<br />
<br />
> SEO related changes

- en/components/general/angular-grid-overview-guide.md
- en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md
- en/components/grid/grid.md
- en/components/list.md
Closes #2228
Closes #2216
<br />
<br />
<br />
> Seo related updates master

- en/components/avatar.md
- jp/components/avatar.md
Closes #2223  
<br />
<br />
<br />
> docs(avatar): correct wrong snippet code

- package-lock.json
- package.json
Change the link of UX item navigation
<br />
<br />
<br />
> Update docfx version to 2.7.9

- en/components/overlay_main.md
- en/components/overlay_position.md
- en/components/select.md
- en/components/toggle.md
Closes # 
<br />
<br />
<br />
> Move target from position to overlay settings

- en/components/grid/grid.md
Closes # 
<br />
<br />
<br />
> chore(*): Update Grid page to remove Diagram kwd

- en/components/combo.md
- en/components/combo_cascading.md
- en/components/combo_features.md
- en/components/combo_remote.md
- en/components/combo_templates.md
Related to #2246
<br />
<br />
<br />
> refactor(combo): Update headers structure #2246

- en/components/display_density.md
- en/components/roundness.md
- en/components/shadows.md
- en/components/themes/component-themes.md
- en/components/themes/global-theme.md
- en/components/themes/index.md
- en/components/themes/palette.md
- en/components/themes/printing-styles.md
- en/components/themes/schemas.md
- en/components/themes/themes-list/bootstrap.md
- en/components/themes/themes-list/fluent.md
- en/components/themes/themes-list/indigo.md
- en/components/themes/themes-list/material.md
- en/components/themes/typography.md
Related to #2246
<br />
<br />
<br />
> refactor(styling and themes):Update headers #2246

- en/components/grids_and_lists.md
- package-lock.json
- package.json
> Update grids and lists topic and docfx-template

- en/components/grids_and_lists.md
> Change sample in grids and lists topic

- en/components/grids_and_lists.md
- package-lock.json
- package.json
> Update grids and lists topic

- en/components/grids_templates/excel_style_filtering.md
Closes #2278 
<br />
<br />
<br />
> refactor(esf): update esf interactions section

- en/components/navbar.md
- en/components/navdrawer.md
Related to https://github.com/IgniteUI/trial-watermark/issues/68
<br />
<br />
<br />
> refactor(menus):Update header structure

- en/components/avatar.md
- en/components/card.md
- en/components/carousel.md
- en/components/dock-manager.md
- en/components/expansion_panel.md
- en/components/layout.md
- en/components/splitter.md
- en/components/tabbar.md
- en/components/tabs.md
Related to https://github.com/IgniteUI/trial-watermark/issues/68
<br />
<br />
<br />
> refactor(layouts):Update header structure

- en/components/calendar.md
Closes #2289 
<br />
<br />
<br />
> Calendar Keyboard navigation section topic update

- en/components/grid/grid.md
- en/components/toc.yml
- jp/components/grid/grid.md
- jp/components/toc.yml
Closes #2304 
<br />
<br />
<br />
> Set update labels and update grid topic with nested props feat

- en/components/banner.md
- en/components/snackbar.md
- en/components/toast.md
Related to https://github.com/IgniteUI/trial-watermark/issues/68#event-3866373181
<br />
<br />
<br />
> refactor(notifications): Update header structure

- en/components/date_range_picker.md
- en/components/date_time_editor.md
- en/components/month_picker.md
- en/components/time_picker.md
Related to https://github.com/IgniteUI/trial-watermark/issues/68#event-3866373181
<br />
<br />
<br />
> refactor(scheduling): Update header structure

- en/components/grid/grid.md
- en/components/grids_templates/summaries.md
- en/components/toc.yml
Closes #2303 
<br />
<br />
<br />
> Add docs for pipeArgs new input and operate new params

- en/components/exporter_csv.md
- en/components/exporter_excel.md
- en/components/localization.md
- en/components/transaction-classes.md
- en/components/transaction-how-to-use.md
- en/components/transaction.md
Related to https://github.com/IgniteUI/trial-watermark/issues/68#event-3866373181
<br />
<br />
<br />
> refactor(services): Update header structure-master

- en/components/grids_and_lists.md
> Fixing sections

- en/components/grids_and_lists.md
> Fixing sections (master)

- en/components/grids_templates/selection.md
Closes #2311 
<br />
<br />
<br />
> Selection topic update

- en/components/hierarchicalgrid/hierarchical_grid.md
Closes # 
<br />
<br />
<br />
> refactor(hierarchical-grid): Update header structure

- en/components/grids_templates/paging.md
Closes # https://github.com/IgniteUI/trial-watermark/issues/79
<br />
<br />
<br />
> refactor (grid paging): Content update-vnext

- en/components/grids_templates/paging.md
Closes # https://github.com/IgniteUI/trial-watermark/issues/79
<br />
<br />
<br />
> refactor (grid paging): Content update-master

- IgniteUIDocFX.nuspec
> Removing the web.config from files

- en/components/list.md
Closes # https://github.com/IgniteUI/trial-watermark/issues/78
<br />
<br />
<br />
> refactor (list): Content update -master

- en/components/grids_templates/search.md
Closes # https://github.com/IgniteUI/trial-watermark/issues/82
<br />
<br />
<br />
> refactor (search): content update -vnext

- en/components/grids_templates/search.md
Closes # https://github.com/IgniteUI/trial-watermark/issues/82
<br />
<br />
<br />
> refactor (search): content update -master

- en/components/grids_templates/cell_selection.md
- en/components/grids_templates/column_selection.md
- en/components/grids_templates/row_selection.md
- en/components/grids_templates/selection.md
Closes this [task](https://github.com/IgniteUI/trial-watermark/issues/75)
> Change Grid selection topics (master)

- en/components/treegrid/tree-grid.md
Closes # 
<br />
<br />
<br />
> refactor(tree-grid): Update header structure-vnext

- en/components/treegrid/tree-grid.md
Closes # 
<br />
<br />
<br />
> refactor(tree-grid): Update header structure-master

- package-lock.json
- package.json
> Update template to 2.8.4-beta.0 (vNext)

- package-lock.json
- package.json
> Update docfx template to 2.8.4-beta.0 (master)

- .github/workflows/node.js.yml
- package.json
Closes # 
<br />
<br />
<br />
> Add gh actions workflow

- en/components/hierarchicalgrid/hierarchical-grid.md
- en/components/treegrid/tree-grid.md
- package-lock.json
- package.json
> Updating template to 2.8.4 (vNext)

- en/components/hierarchicalgrid/hierarchical-grid.md
- en/components/treegrid/tree-grid.md
- package-lock.json
- package.json
> Updating template to 2.8.4 (master)

- en/components/combo.md
- en/components/grid/grid.md
- en/components/grid/groupby.md
- en/components/grids-and-lists.md
- en/components/grids_templates/advanced-filtering.md
- en/components/grids_templates/excel-style-filtering.md
- en/components/grids_templates/filtering.md
- en/components/grids_templates/paging.md
- en/components/grids_templates/search.md
- en/components/list.md
- en/components/treegrid/tree-grid.md
- jp/components/combo.md
- jp/components/grid/grid.md
- jp/components/grid/groupby.md
- jp/components/grids-and-lists.md
- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/excel-style-filtering.md
- jp/components/grids_templates/filtering.md
- jp/components/grids_templates/paging.md
- jp/components/grids_templates/search.md
- jp/components/list.md
- jp/components/treegrid/tree-grid.md
Related to https://github.com/IgniteUI/trial-watermark/issues/87
All changes mentioned in the excel file are applied
> SEO Updates meta keywords, desc and title

- jp/components/combo-features.md
- jp/components/combo.md
- jp/components/general-licensing.md
- jp/components/general/angular-grid-overview-guide.md
- jp/components/grid/grid.md
- jp/components/grid/groupby.md
- jp/components/grids-and-lists.md
- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/excel-style-filtering.md
- jp/components/grids_templates/filtering.md
- jp/components/grids_templates/keyboard-navigation.md
- jp/components/grids_templates/paging.md
- jp/components/grids_templates/row-selection.md
- jp/components/grids_templates/search.md
- jp/components/grids_templates/selection.md
- jp/components/hierarchicalgrid/hierarchical-grid.md
- jp/components/list.md
- jp/components/treegrid/tree-grid.md
> Updating JP - vnext

- en/components/grids_templates/paging.md
- jp/components/grids_templates/paging.md
- kr/components/grids_templates/paging.md
- package-lock.json
Closes # 
<br />
<br />
<br />
> fix(*): paginator theme link was broken - vNEXT

- en/components/grids_templates/paging.md
- jp/components/grids_templates/paging.md
- kr/components/grids_templates/paging.md
- package-lock.json
Closes # 
<br />
<br />
<br />
> fix(*): paginator theme link was broken - master

- en/components/grids_templates/column-selection.md
- jp/components/grids_templates/column-selection.md
Related to IgniteUI/igniteui-angular-samples#2340
<br />
<br />
<br />
> Fixes column selection samples not being styled w/ theming widget

- package-lock.json
- package.json
Closes #2447
<br />
<br />
<br />
> update docfx-template package  version

- package-lock.json
- package.json
Closes #2447 
<br />
<br />
<br />
> Update docfx template version

- en/components/material-icons-extended.md
- jp/components/material-icons-extended.md
Closes #2461 
<br />
<br />
<br />
> Fix material icons extended page -vnext

- en/components/material-icons-extended.md
- jp/components/material-icons-extended.md
Closes #2461 
<br />
<br />
<br />
> Fix material icons extended page -master

- en/components/grids_templates/toolbar.md
Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/2361
<br />
<br />
<br />
> fix(toolbar): update the styling section of the topic

- en/components/general/angular-grid-overview-guide.md
- en/components/grids_templates/live-data.md
- jp/components/general/angular-grid-overview-guide.md
- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-docfx/issues/2367
> Add code view

- en/components/general/angular-grid-overview-guide.md
- en/components/grids_templates/live-data.md
- jp/components/general/angular-grid-overview-guide.md
- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-docfx/issues/2367
> Add Code View - master

- en/components/banner.md
- en/components/card.md
- en/components/date-picker.md
- en/components/divider.md
- en/components/grids_templates/collapsible-column-groups.md
- en/components/grids_templates/live-data.md
- en/components/grids_templates/row-selection.md
- en/components/mask.md
- en/components/navdrawer.md
- en/components/toast.md
- en/components/toggle.md
- jp/components/banner.md
- jp/components/card.md
- jp/components/date-picker.md
- jp/components/divider.md
- jp/components/grids_templates/collapsible-column-groups.md
- jp/components/grids_templates/live-data.md
- jp/components/grids_templates/row-selection.md
- jp/components/mask.md
- jp/components/navdrawer.md
- jp/components/toast.md
- jp/components/toggle.md
Closes #2472 
<br />
<br />
<br />
> Update topics first iframe -vnext

- en/components/banner.md
- en/components/card.md
- en/components/date-picker.md
- en/components/divider.md
- en/components/grids_templates/collapsible-column-groups.md
- en/components/grids_templates/live-data.md
- en/components/grids_templates/row-selection.md
- en/components/mask.md
- en/components/navdrawer.md
- en/components/toast.md
- en/components/toggle.md
- jp/components/banner.md
- jp/components/card.md
- jp/components/date-picker.md
- jp/components/divider.md
- jp/components/grids_templates/collapsible-column-groups.md
- jp/components/grids_templates/live-data.md
- jp/components/grids_templates/row-selection.md
- jp/components/mask.md
- jp/components/navdrawer.md
- jp/components/toast.md
- jp/components/toggle.md
Closes #2472 
<br />
<br />
<br />
> Update topics first iframe -master

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update docfx-template to 2.9.1

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update to 2.9.1

- en/components/general/angular-grid-overview-guide.md
- en/components/grids-and-lists.md
- jp/components/general/angular-grid-overview-guide.md
- jp/components/grids-and-lists.md
- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/2387
<br />
<br />
<br />
> Add crmDemoBaseUrl vnext

- en/components/drop-down.md
Related to: IgniteUI/igniteui-angular/issues/8656
<br />
<br />
<br />
> docs(drop-down): add info about prefix, suffix and divider

- en/components/general/angular-grid-overview-guide.md
- en/components/grids-and-lists.md
- jp/components/general/angular-grid-overview-guide.md
- jp/components/grids-and-lists.md
- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Add crmDemoBaseUrl master

- en/components/calendar.md
- en/components/chip.md
- en/components/date-picker.md
- en/components/texthighlight.md
- jp/components/chip.md
- jp/components/date-picker.md
- jp/components/texthighlight.md
- kr/components/texthighlight.md
Closes #2451 
Closes this [task ](https://github.com/IgniteUI/igniteui-docfx-template/issues/250)
Closes #2471
> Remove topics duplicate iframe ids

- en/components/calendar.md
- en/components/chip.md
- en/components/date-picker.md
- en/components/texthighlight.md
- jp/components/chip.md
- jp/components/date-picker.md
- jp/components/texthighlight.md
- kr/components/texthighlight.md
Closes #2451 
Closes this [task ](https://github.com/IgniteUI/igniteui-docfx-template/issues/250)
Closes #2471
> Remove topics duplicate iframe ids (master)

- en/components/grids_templates/sizing.md
- kr/components/grids_templates/sizing.md
Closes #1466
<br />
<br />
<br />
> Fix incomplete sentence.

- en/components/drag-drop.md
- jp/components/drag-drop.md
Closes #2023
<br />
<br />
<br />
> Add section for the igxDragIgnore directive

- README.md
Closes # 
<br />
<br />
<br />
> Update readme with powershell specific command

- jp/components/drag-drop.md
- jp/components/grids_templates/sizing.md
- jp/components/hierarchicalgrid/hierarchical-grid.md
> Localization 0912 vnext

- package-lock.json
- package.json
> Update templ 293 (vnext)

- package-lock.json
- package.json
> Updating template to 2.9.3 (master)

- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-docfx-template/issues/254
> Update to 2.9.4 vNext

- en/components/radio-button.md
Related to: IgniteUI/igniteui-angular/issues/8713
<br />
<br />
<br />
> docs(radio-button): include info for the radio group alignment

- en/components/display-density.md
- en/components/shadows.md
- en/components/themes/component-themes.md
- en/components/themes/index.md
- en/components/themes/palette.md
> docs(theming): fix broken links

- en/components/animations.md
- en/components/toc.yml
Related issue: IgniteUI/igniteui-angular/issues/8724
<br />
<br />
<br />
> docs(theming): provide documentation for animations

- en/components/combo.md
Closes #2435 
<br />
<br />
<br />
> Adding a note for the combo's default type.

- en/components/input-group-reactive-forms.md
- jp/components/input-group-reactive-forms.md
- kr/components/input-group-reactive-forms.md
Closes #2058 
<br />
<br />
<br />
> Removing the FormControl() call.

- en/components/shadows.md
Fix typo in elevations article.
> Fix typo in elevations article

- package-lock.json
- package.json
> Update template to 2.9.5(vnext)

- package-lock.json
- package.json
> Updating template to 2.9.5 (master)

- en/components/icon.md
- en/components/material-icons-extended.md
Related to IgniteUI/igniteui-angular/issues/8769
<br />
<br />
<br />
> docs(icon): update icon inputs names

- en/components/input-group.md
Closes # 
<br />
<br />
<br />
> refactor(input-group): add theme section

- en/web.config
- jp/web.config
- kr/web.config
Closes # 
<br />
<br />
<br />
> Fix redirection rules -vnext

- en/web.config
- jp/web.config
- kr/web.config
Closes #2545 
<br />
<br />
<br />
> Fix redirection rules -master

- en/components/grids_templates/advanced-filtering.md
- en/components/grids_templates/batch-editing.md
- en/components/grids_templates/column-hiding.md
- en/components/grids_templates/filtering.md
- en/components/grids_templates/row-editing.md
- en/components/treegrid/tree-grid.md
- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/batch-editing.md
- jp/components/grids_templates/column-hiding.md
- jp/components/grids_templates/filtering.md
- jp/components/grids_templates/row-editing.md
- jp/components/treegrid/tree-grid.md
Closes #2518
<br />
<br />
<br />
> docs(toolbar): remove deprecated properties -master

- en/web.config
- jp/web.config
- kr/web.config
Closes #2548 
<br />
<br />
<br />
> Add additional redirect rule for overlay -vnext

- en/web.config
- jp/web.config
- kr/web.config
Closes #2548 
<br />
<br />
<br />
> Add additional redirect rule for overlay -master

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Add slash to _rel path - staging

- en/web.config
- package-lock.json
- package.json
Closes #2560 
<br />
<br />
<br />
> Fix missing scripts on iis

- en/components/grids_templates/export-excel.md
Closes #2546 
<br />
<br />
<br />
> create grouped grid section and edit limitations

- en/components/grids_templates/cell-editing.md
- jp/components/grids_templates/cell-editing.md
Closes #2550 
<br />
<br />
<br />
> Adding a note about the focus in templated cells - master #2550

- en/components/grids_templates/cell-editing.md
- jp/components/grids_templates/cell-editing.md
Closes #2550
<br />
<br />
<br />
> Adding a note about the focus in the templated cells - vNext #2550

- en/components/carousel.md
Closes #2552
<br />
<br />
<br />
> Carousel - Add a11y section vNext

- en/components/carousel.md
Closes #2552
<br />
<br />
<br />
> Carousel - Add a11y section master

- en/components/carousel.md
- en/components/list.md
- en/components/navbar.md
Closes #2566  
<br />
<br />
<br />
> fix(Events): Updated renamed events (CodeX)

- en/components/grids_templates/excel-style-filtering.md
Closes #2567 
<br />
<br />
<br />
> Add Formatted Filtering Strategy Section

- en/components/exporter-csv.md
- en/components/exporter-excel.md
- en/components/grids_templates/export-excel.md
- en/components/grids_templates/toolbar.md
Closes #2566  
<br />
<br />
<br />
> fix(Exporters): Updated renamed events.

- en/components/grid/grid.md
- en/components/grids_templates/column-types.md
- en/components/grids_templates/editing.md
- en/components/grids_templates/summaries.md
- en/components/toc.yml
Closes #2576
<br />
<br />
<br />
> Update toc and add column-types topic

- en/components/grids_templates/row-selection.md
- en/components/grids_templates/selection.md
Closes #2572
<br />
<br />
<br />
> modify selection topics by adding multipleCascade

- en/components/grids_templates/column-types.md
Related to IgniteUI/igniteui-docfx#2576
> Add live-editing iframe to column-data-types topic

- en/components/general/update-guide.md
- en/components/grids_templates/editing.md
- en/components/grids_templates/paging.md
- en/components/grids_templates/remote-data-operations.md
Reverts IgniteUI/igniteui-docfx#2586
> Revert "update paging, editing and upgrdade guide topics"

- en/components/grids_templates/paging.md
- en/components/grids_templates/remote-data-operations.md
Updates regarding https://github.com/IgniteUI/igniteui-angular-samples/pull/2479
> Paging theming snippets update

- package-lock.json
Closes # 
<br />
<br />
<br />
> Package lock update

- en/components/date-picker.md
> chore(date-picker): revert date-picker topic

- en/components/tabs.md
Closes #2583  
<br />
<br />
<br />
> fix(Tabs): Removed non-existing links.

- package-lock.json
- package.json
Reenable DV components theming
> Update to docfx-template 3.0.0-alpha.3 Reenable DV components theming

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> Remove duplicate content - vnext

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> Remove duplicate content - master

- en/components/grids-and-lists.md
- en/components/grids_templates/live-data.md
- en/components/treegrid/aggregations.md
- jp/components/grids-and-lists.md
- jp/components/grids_templates/live-data.md
- jp/components/treegrid/aggregations.md
- kr/components/grid/grid.md
- kr/components/treegrid/aggregations.md
Related to #2632
<br />
<br />
<br />
> Fix live-data page code-view -master

- en/components/interactivity/right-to-left-support.md
- jp/components/interactivity/right-to-left-support.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> Update rtl page code-view generation -vnext

- package-lock.json
- package.json
This is the fix for the theming issue
> Update tempalte to 3.0.0-alpha.8

- en/components/grids_templates/cell-editing.md
- en/components/list.md
- en/components/time-picker.md
- en/components/toast.md
- jp/components/grids_templates/cell-editing.md
- jp/components/list.md
- jp/components/time-picker.md
- jp/components/toast.md
- kr/components/grids_templates/virtualization.md
- kr/components/list.md
- kr/components/time-picker.md
- kr/components/toast.md
Closes #2613 
<br />
<br />
<br />
> docs(toast): update toast methods names

- en/components/general/update-guide.md
Related to: IgniteUI/igniteui-angular/issues/9118
<br />
<br />
<br />
> docs(update-guide): list typography refactoring changes

- en/components/general/update-guide.md
Closes #2618  
<br />
<br />
<br />
> docs(themes): add avatar update guide

- en/components/button.md
- en/components/grids_templates/excel-style-filtering.md
- en/components/roundness.md
Closes #2646 
<br />
<br />
<br />
> refactor(button): update button property names

- en/components/grids_templates/live-data.md
https://github.com/IgniteUI/igniteui-angular-samples/issues/2521
> Adding of live-data topic section

- en/components/general/data-analysis.md
- en/components/general/ssr-rendering.md
- jp/components/general/data-analysis.md
- jp/components/general/ssr-rendering.md
Closes #2657
<br />
<br />
<br />
> Fix data-analysis and ssr-rendering paths -vnext

- en/components/general/data-analysis.md
- en/components/general/ssr-rendering.md
- jp/components/general/data-analysis.md
- jp/components/general/ssr-rendering.md
Closes #2657
<br />
<br />
<br />
> Fix data-analysis and ssr-rendering paths -master

- en/components/grids_templates/live-data.md
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/2521
> Add Code View for FinJS with Dock Manager - master

- package-lock.json
- package.json
Closes #2637
<br />
<br />
<br />
> Update template version -vnext

- en/components/grids_templates/row-adding.md
Related: IgniteUI/igniteui-angular#8964
<br />
<br />
<br />
> Add customizing section to row adding topic

- en/components/grids_templates/live-data.md
Closes # 
<br />
<br />
<br />
> Fix problem with template

- en/components/general/how-to/signal-r-service-live-data.md
> Address minor topic typos

- en/components/general/how-to/signal-r-service-live-data.md
> Fix minor typos master

- package-lock.json
- package.json
Closes #2687 
Related to https://github.com/IgniteUI/igniteui-docfx-template/issues/228
> Updating docfx template to 3rc 0

- en/components/card.md
- en/components/general/update-guide.md
- en/components/themes/palettes.md
- en/components/themes/sass/component-themes.md
- en/components/themes/sass/roundness.md
- kr/components/general/update-guide.md
- kr/components/roundness.md
Closes # 
<br />
<br />
<br />
> docs(themes): fix typos and paths

- en/components/overlay-position.md
- en/components/overlay-scroll.md
- en/components/overlay.md
Closes #6063
<br />
- [x ] use spell checker tool (VS Code, Grammarly, Microsoft Editor)
- [x ] check if code blocks match the code in StackBlitz demo
<br />
<br />
> Add detach to overlay service

- en/components/tabbar.md
- en/components/toc.yml
Closes #2690 
<br />
<br />
<br />
> Updated BottomNav topic after refactoring.

- en/components/chip.md
- en/components/general/cli-overview.md
- en/components/general/cli/auth-template.md
- en/components/general/cli/step-by-step-guide.md
- en/components/general/data-analysis.md
- en/components/general/getting-started.md
- en/components/general/update-guide.md
- en/components/general/wpf-to-angular-guide/create-first-angular-app.md
- en/components/general/wpf-to-angular-guide/create-ui-with-components.md
- en/components/general/wpf-to-angular-guide/layout.md
- en/components/general/wpf-to-angular-guide/wpf-to-angular-guide.md
- en/components/grids_templates/collapsible-column-groups.md
- en/components/grids_templates/toolbar.md
- en/components/hierarchicalgrid/load-on-demand.md
- en/components/transaction.md
- jp/components/chip.md
- jp/components/general/cli-overview.md
- jp/components/general/cli/auth-template.md
- jp/components/general/cli/step-by-step-guide.md
- jp/components/general/data-analysis.md
- jp/components/general/getting-started.md
- jp/components/general/update-guide.md
- jp/components/general/wpf-to-angular-guide/create-first-angular-app.md
- jp/components/general/wpf-to-angular-guide/create-ui-with-components.md
- jp/components/general/wpf-to-angular-guide/layout.md
- jp/components/general/wpf-to-angular-guide/wpf-to-angular-guide.md
- jp/components/grids_templates/collapsible-column-groups.md
- jp/components/hierarchicalgrid/load-on-demand.md
- jp/components/transaction.md
Closes #2686 
<br />
<br />
<br />
> Update pages to be responsive - vnext

- en/components/chip.md
- en/components/general/cli-overview.md
- en/components/general/cli/auth-template.md
- en/components/general/cli/step-by-step-guide.md
- en/components/general/data-analysis.md
- en/components/general/getting-started.md
- en/components/general/update-guide.md
- en/components/general/wpf-to-angular-guide/create-first-angular-app.md
- en/components/general/wpf-to-angular-guide/create-ui-with-components.md
- en/components/general/wpf-to-angular-guide/layout.md
- en/components/general/wpf-to-angular-guide/wpf-to-angular-guide.md
- en/components/grids_templates/collapsible-column-groups.md
- en/components/grids_templates/toolbar.md
- en/components/hierarchicalgrid/load-on-demand.md
- en/components/transaction.md
- jp/components/chip.md
- jp/components/general/cli-overview.md
- jp/components/general/cli/auth-template.md
- jp/components/general/cli/step-by-step-guide.md
- jp/components/general/data-analysis.md
- jp/components/general/getting-started.md
- jp/components/general/update-guide.md
- jp/components/general/wpf-to-angular-guide/create-first-angular-app.md
- jp/components/general/wpf-to-angular-guide/create-ui-with-components.md
- jp/components/general/wpf-to-angular-guide/layout.md
- jp/components/general/wpf-to-angular-guide/wpf-to-angular-guide.md
- jp/components/grids_templates/collapsible-column-groups.md
- jp/components/hierarchicalgrid/load-on-demand.md
- jp/components/transaction.md
Closes #2686 
<br />
<br />
<br />
> Update pages to be responsive - master

- en/components/general/how-to/signal-r-service-live-data.md
- en/components/grid/grid.md
Closes # 
<br />
<br />
<br />
> SEO changes

- package-lock.json
- package.json
> Updating template to 3.0.0-rc.1

- en/components/tree.md
Closes #2731 
<br />
<br />
<br />
> fix(tree): smaller height of demos in tree topic

- en/components/grids_templates/excel-style-filtering.md
- en/components/navbar.md
- en/components/tabbar.md
- en/components/tabs.md
Closes #2743 
<br />
<br />
<br />
> Fixed broken links - ESF, Tabs, Bottom Nav & Navbar - vNext

- jp/components/exporter-excel.md
- jp/components/general-breaking-changes-dv.md
- jp/components/general-licensing.md
- jp/components/general/update-guide.md
- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/cell-editing.md
- jp/components/grids_templates/column-types.md
- jp/components/grids_templates/editing.md
- jp/components/grids_templates/excel-style-filtering.md
- jp/components/grids_templates/export-excel.md
- jp/components/grids_templates/filtering.md
- jp/components/grids_templates/live-data.md
- jp/components/grids_templates/row-drag.md
- jp/components/hierarchicalgrid/hierarchical-grid.md
- jp/components/navbar.md
- jp/components/tabbar.md
- jp/components/tabs.md
- jp/components/toc.yml
- jp/components/tree.md
> [JP] Adding latest localized changes

- jp/components/grids_templates/batch-editing.md
> [JP] Updating Batch Editing topic

- en/components/exporter-csv.md
Closes #2749 
Closes #2750 
<br />
<br />
<br />
> Add TreeGrid and HierarchicalGrid links and remove unnecessary note

- en/components/grids_templates/column-hiding.md
- en/components/grids_templates/paging.md
- en/components/grids_templates/sorting.md
Closes #2748 
<br />
<br />
<br />
> fix(Grids): Fixed broken sass links

- en/components/grids_templates/column-selection.md
Closes #2753 
<br />
<br />
<br />
> fix(column-selection): fix broken links

- en/components/grids_templates/state-persistence.md
> Fix broken links in TreeGrid State Persistence topic #2764 

- en/components/grids_templates/column-resizing.md
- en/components/grids_templates/row-pinning.md
> fix(docs): Fix two broken links

- en/components/grids_templates/paging.md
Closes # 
<br />
<br />
<br />
> Add reusable paginator sample for the TreeGrid topic

- en/components/grids_templates/column-types.md
- en/components/grids_templates/multi-column-headers.md
Closes #2762
Closes #2763 
<br />
<br />
<br />
> fix(Grid): Fixed broken links in Column Data Types and Multi-column headers topics

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> Fix leftover button reference from copied paragraph

- en/components/calendar.md
- en/components/date-picker.md
- en/components/date-range-picker.md
- en/components/date-time-editor.md
- en/components/general/update-guide.md
- en/components/time-picker.md
- en/components/toc.yml
- jp/components/toc.yml
Closes #2691 
<br />
<br />
<br />
> feat(date-picker, time-picker): update pickers' topics

- package-lock.json
- package.json
> Update template to 3.0.0-rc.4

- en/components/date-picker.md
- en/components/date-time-editor.md
> Fix topics typos

- en/components/grids_templates/paging.md
- jp/components/grids_templates/paging.md
Closes #2758 
<br />
<br />
<br />
> fix(docs): Remove disabled demo buttons in paging topic -vnext

- en/components/date-range-picker.md
> Fix topics links vNext

- en/components/general/localization.md
> docs: add BG as a language

- en/components/themes/sass/configuration.md
- jp/components/themes/sass/configuration.md
Closes # 
<br />
<br />
<br />
> fix(themes): remove a line

- en/components/general/localization.md
Closes #2802
<br />
<br />
<br />
> Update app localization topic

- en/components/themes/sass/global-themes.md
- en/components/themes/sass/palettes.md
- en/components/themes/sass/typography.md
> Clean up themes articles

- en/components/general/localization.md
> Add 9 new languages to app localization topic - master

- jp/components/general/localization.md
> [JP] Adding 9 languages to the localization topic - vnext

- en/components/date-picker.md
- en/components/time-picker.md
> Add date & time picker in Angular forms section-vNext

- en/components/style-guide.md
> Adding styling guide dev

- jp/components/date-picker.md
- jp/components/time-picker.md
> [JP] Date & time picker in Angular forms - vnext

- en/components/themes/sass/configuration.md
Closes # 
<br />
<br />
<br />
> refactor(themes): add info about scrollbar config

- en/components/grids_templates/editing.md
- jp/components/grids_templates/editing.md
Closes #2829
<br />
<br />
<br />
> Fix rowEditable links for editing topics - vnext

- en/components/grids_templates/editing.md
- jp/components/grids_templates/editing.md
Closes #2829 
<br />
<br />
<br />
> Fix rowEditable links for editing topics - master

- en/components/general/getting-started.md
- en/components/general/ignite-ui-licensing.md
> Update licensing topic

- en/components/general/getting-started.md
- en/components/general/ignite-ui-licensing.md
> Licensing topic master

- jp/components/themes/sass/configuration.md
> [JP] refactor(themes): add info about scrollbar config - vnext

- package-lock.json
- package.json
Related to https://github.com/IgniteUI/igniteui-docfx-template/issues/318
> Update to docfx template v3.0.9 - new theme

- en/components/snackbar.md
- en/components/toast.md
Related to: 
IgniteUI/igniteui-angular-samples/issues/2728
IgniteUI/igniteui-angular/issues/9677
IgniteUI/igniteui-angular/issues/9678
<br />
<br />
<br />
> docs(snackbar, toast): update docs according to the latest changes

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update template version with japanese search -vnext

- en/components/banner.md
- en/components/grids-and-lists.md
- en/components/grids_templates/cell-editing.md
- en/components/grids_templates/column-moving.md
- en/components/grids_templates/summaries.md
- en/components/slider/slider.md
- en/components/snackbar.md
- en/components/toast.md
- en/web.config
- jp/components/banner.md
- jp/components/grids-and-lists.md
- jp/components/grids_templates/cell-editing.md
- jp/components/grids_templates/column-hiding.md
- jp/components/grids_templates/column-moving.md
- jp/components/grids_templates/column-resizing.md
- jp/components/grids_templates/multi-column-headers.md
- jp/components/grids_templates/paging.md
- jp/components/grids_templates/sorting.md
- jp/components/grids_templates/summaries.md
- jp/components/slider/slider.md
- jp/components/snackbar.md
- jp/components/toast.md
- jp/components/tree.md
- jp/web.config
Closes #2789 
<br />
<br />
<br />
> Fix topics links and redirects

- en/components/grid/grid.md
- en/components/grids_templates/column-hiding.md
- en/components/grids_templates/toolbar.md
Closes #2878
Add samples for:
New overlaySettings input
Expose column input for template context
Related to
Expose docs and samples for overlaySetting toolbar action
Create sample: column input for template context
> Topic updates based on new features

- en/components/action-strip.md
- jp/components/action-strip.md
Related to IgniteUI/igniteui-angular/pull/9804
<br />
<br />
<br />
> docs(action-strip): rename color property

- en/components/general/localization.md
- package-lock.json
- package.json
Related to # https://github.com/IgniteUI/igniteui-angular-samples/issues/2731
<br />
<br />
<br />
> Add explicitEditor for localization code-view -vnext

- en/components/general/localization.md
- package-lock.json
- package.json
Related to # https://github.com/IgniteUI/igniteui-angular-samples/issues/2731
<br />
<br />
<br />
> Add explicitEditor for localization code-view -master

- en/components/general/ignite-ui-licensing.md
Closes # 
<br />
<br />
<br />
> fix(licensing): formatting changes

- en/components/accordion.md
Closes #2891 
<br />
<br />
<br />
> fix(accordion): broken links

- en/components/combo.md
> Fix minor typo, add link for allowCustomValues, remove trailing whitespaces

- en/components/accordion.md
Closes #2912 
<br />
<br />
<br />
> Update Accordion topic with SEO improvements

- en/components/general/localization.md
- jp/components/general/localization.md
- kr/components/general/localization.md
Related TO:
https://github.com/IgniteUI/igniteui-angular/issues/6602
<br />
<br />
<br />
> chore(i18n): Point i18n links to igniteui-angular - master

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> change the list item type

- en/components/general/update-guide.md
- en/components/grids_templates/cell-editing.md
- jp/components/grids_templates/cell-editing.md
Closes # 
<br />
<br />
<br />
> remove notes from cell editing, which are not valid anymore

- en/components/toc.yml
Closes # 
<br />
<br />
<br />
> fix(schematics, cli): order topics

- en/components/grids_templates/column-hiding.md
Closes #2929 
<br />
<br />
<br />
> fix broken link

- en/components/exporter-csv.md
- en/components/exporter-excel.md
- en/components/grids_templates/export-excel.md
Removed codesandbox live-editing buttons for exporters samples.
<br />
<br />
<br />
> chore(*): Excluded codesandbox for exporters

- en/components/general/ignite-ui-licensing.md
Closes # 
<br />
<br />
<br />
> Update licensing topic content -vnext

- en/components/action-strip.md
- en/components/general/how-to/how-to-perform-crud.md
- en/components/grid/grid.md
- en/components/grids_templates/batch-editing.md
- en/components/grids_templates/cell-editing.md
- en/components/grids_templates/editing.md
- en/components/grids_templates/row-editing.md
- en/components/hierarchicalgrid/hierarchical-grid.md
- en/components/toc.yml
- en/components/transaction.md
- jp/components/action-strip.md
- jp/components/grid/grid.md
- jp/components/grids_templates/batch-editing.md
- jp/components/grids_templates/cell-editing.md
- jp/components/grids_templates/editing.md
- jp/components/grids_templates/row-editing.md
- jp/components/hierarchicalgrid/hierarchical-grid.md
- jp/components/toc.yml
- jp/components/transaction.md
- kr/components/action-strip.md
- kr/components/grid/grid.md
- kr/components/grids_templates/batch-editing.md
- kr/components/grids_templates/editing.md
- kr/components/hierarchicalgrid/hierarchical-grid.md
Closes # 
<br />
<br />
<br />
> add crud topic

- en/components/date-range-picker.md
Related to IgniteUI/igniteui-angular-samples#2768
<br />
<br />
<br />
> feat(date-range-picker): add custom action buttons sample

- en/components/grids_templates/filtering.md
Closes #2965 
<br />
<br />
<br />
> feat(tree-grid): add section for the matching records only filtering strategy to the filtering topic

- en/components/general/localization.md
Closes # 
<br />
<br />
<br />
> feat(i18n): add norwegian (nb) language

- en/components/drop-down.md
Closes # 
<br />
<br />
<br />
> fix(drop-down): seo improvements

- en/components/grids_templates/row-adding.md
Closes #2964  
<br />
<br />
<br />
> docs(row-adding): add info about the new beginAddRow methods

- en/components/grids_templates/row-adding.md
Closes #2964   
<br />
<br />
<br />
> docs(row-adding): add info about the new beginAddRow methods - vNext

- en/components/grids_templates/export-excel.md
Closes #2976 
<br />
<br />
<br />
> Add section in excel export topic for freezing header option

- en/components/grids_templates/conditional-cell-styling.md
- en/components/toc.yml
Closes #2966 
<br />
<br />
<br />
> Add documentationfor the rowClasses/rowStyles inputs for grid

- en/components/grids_templates/state-persistence.md
- jp/components/grids_templates/state-persistence.md
Closes # 
<br />
<br />
<br />
> Update state persistence topic

- package-lock.json
- package.json
Related to #2996 
<br />
<br />
<br />
> Update template version - master

- en/components/stepper.md
Closes #3011 
<br />
<br />
<br />
> remove links to directives and enums

- en/components/dialog.md
Closes # 
<br />
<br />
<br />
> Update dialog topic with focus trap section

- en/components/grids_templates/row-actions.md
- en/components/row-actions.md
- en/components/toc.yml
- jp/components/grids_templates/row-actions.md
Closes # 
<br />
<br />
<br />
> chore(grid):rename action-strip to row actions

- en/components/grids_templates/row-actions.md
This PR updates the link for sample on row actions page for tree grid.
<br />
<br />
<br />
> fix(tree-grid): update link for sample for row actions

- en/components/treegrid/tree-grid.md
Closes #3023 
<br />
<br />
<br />
> fix(tree-grid): remove duplicate sample

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> Adding more breaking changes and updates

- en/components/simple-combo.md
Closes # 
<br />
<br />
<br />
> refactor(simple-combo): update docs for simple combo

- en/components/dialog.md
Closes # 
<br />
<br />
<br />
> Fix dialog section links

- en/components/grids_templates/toolbar.md
- jp/components/grids_templates/toolbar.md
- kr/components/grids_templates/toolbar.md
Closes https://github.com/IgniteUI/igniteui-docfx/issues/3029
<br />
<br />
<br />
> Update toollbar topic

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> docs(update-guide): add additional information regarding themes

- .github/CONTRIBUTING.md
- en/components/grid/grid.md
Closes #3010 
<br />
<br />
<br />
> Final SEO content changes

- en/components/exporter-csv.md
- en/components/exporter-excel.md
- en/components/grids_templates/export-excel.md
- en/components/grids_templates/toolbar.md
Closes #3075  
<br />
<br />
<br />
> add clarification for providing exporter services - vNext

- en/components/linear-progress.md
Closes #3077 
<br />
<br />
<br />
> Add a note about the new animationDuration prop in progress bar 

- package-lock.json
- package.json
Closes [# ](https://github.com/IgniteUI/igniteui-docfx/issues/3085)
<br />
<br />
<br />
> Update docfx-template to 3.0.19

- en/components/grids_templates/paging.md
- en/components/toc.yml
- jp/components/grids_templates/paging.md
- jp/components/toc.yml
Closes #3080  
<br />
<br />
<br />
> fix(toc): removing the pagination category #3080

- en/components/exporter-csv.md
- en/components/exporter-excel.md
- en/components/grids_templates/export-excel.md
- en/components/grids_templates/toolbar.md
Closes #3075  
<br />
<br />
<br />
> add clarification for providing exporter services - master

- en/components/navbar.md
Closes #3086 
<br />
<br />
<br />
> chore(navbar): update topic according to the Icon Buttons usage changes in the samples

- jp/components/navbar.md
Closes # 
<br />
<br />
<br />
> [Localization] Updating JP for #3098

- kr/components/circular-progress.md
Closes #3077
<br />
<br />
<br />
> add examples and documentation for animationDuration property

- en/components/grid/grid.md
- en/components/grids_templates/column-moving.md
- en/components/grids_templates/excel-style-filtering.md
- en/components/grids_templates/multi-column-headers.md
- en/components/grids_templates/row-editing.md
- en/components/treegrid/tree-grid.md
- jp/components/grid/grid.md
- jp/components/grids_templates/column-moving.md
- jp/components/grids_templates/excel-style-filtering.md
- jp/components/grids_templates/multi-column-headers.md
- jp/components/grids_templates/row-editing.md
- jp/components/treegrid/tree-grid.md
- kr/components/grids_templates/column-moving.md
- kr/components/grids_templates/excel-style-filtering.md
- kr/components/grids_templates/multi-column-headers.md
- kr/components/grids_templates/row-editing.md
- kr/components/treegrid/tree-grid.md
Closes #3097 
<br />
<br />
<br />
> Replace column movable prop with the newly exposed moving property in all grid topics

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> update to 3.1.0-alpha.0

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> Update template to 3.1.0-alpha.0

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> fix: update guide with licensed package

- en/components/overlay-styling.md
- jp/components/overlay-styling.md
Closes #3112 
<br />
<br />
<br />
> Fix code snippets in Overlay Styling topic

- en/components/general/update-guide.md
Closes #3122  
<br />
<br />
<br />
> Include the column moving refactoring to the Update Guide

- en/components/general/update-guide.md
- en/components/toast.md
Closes #3124 
<br />
<br />
<br />
> docs(toast): add changes to update guide

- en/components/pivotGrid/pivot-grid.md
- jp/components/pivotgrid/pivot-grid.md
- kr/components/pivotgrid/pivot-grid.md
Closes # 
<br />
<br />
<br />
> docs(pivot): fix wording and repeating

- en/components/themes/misc/bootstrap-theming.md
- jp/components/themes/misc/bootstrap-theming.md
Related to IgniteUI/igniteui-angular/issues/11105
<br />
<br />
<br />
> docs(bootstrap): update palette colors

- en/components/grids_templates/excel-style-filtering.md
Closes #3110 
<br />
<br />
<br />
> docs(treegrid-esf): add tree filter view section

- en/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> docs(*): add a breaking change to update guide

- en/components/interactivity/right-to-left-support.md
- jp/components/interactivity/right-to-left-support.md
Closes #3136  
<br />
<br />
<br />
> chore(tabs): remove the tab component from partially supported RTL

- en/components/pivotGrid/pivot-grid.md
Closes # 
<br />
<br />
<br />
> docs(pivot): Modify the structure of the topic to have SEO optimization

- en/components/grids_templates/conditional-cell-styling.md
- jp/components/grids_templates/conditional-cell-styling.md
Related to https://github.com/IgniteUI/igniteui-angular/issues/11259 and should be merged after https://github.com/IgniteUI/igniteui-angular/pull/11260
<br />
<br />
<br />
> Update existing row styling docs

- en/components/grids_templates/column-types.md
- jp/components/grids_templates/column-types.md
Closes #3159  
<br />
<br />
<br />
> Fix code snippet for Custom Editing Template section

- en/components/grid/grid.md
Closes #3162 
<br />
<br />
<br />
> Add turorial video in the grid topic

- en/components/grid/grid.md
- jp/components/grid/grid.md
- kr/components/grid/grid.md
Closes #3162 
<br />
<br />
<br />
> Add embedded video

- en/components/grid/grid.md
- jp/components/grid/grid.md
- kr/components/grid/grid.md
Closes #3162 
<br />
<br />
<br />
> add embeddded video

- en/components/grids_templates/keyboard-navigation.md
- jp/components/grids_templates/keyboard-navigation.md
Closes #3166
Should be tested together with https://github.com/IgniteUI/igniteui-angular-samples/pull/2986
<br />
<br />
<br />
> docs(ghrid): Increase HGrid Keyboard Nav sample height

- en/components/date-picker.md
- kr/components/date-picker.md
> Update date-picker docs

- en/components/combo.md
Closes # 
<br />
<br />
<br />
> fix(combo): revert back igxCombo single selection snippet

- en/components/grids_templates/multi-column-headers.md
Closes #3147
<br />
<br />
<br />
> add inform text for Pinning w/ Multi-Column Header

- en/components/general/update-guide.md
- en/components/interactivity/accessibility-compliance.md
- en/components/interactivity/right-to-left-support.md
- en/components/themes/index.md
- en/components/themes/sass/configuration.md
- en/components/themes/sass/global-themes.md
Closes #3185 
<br />
<br />
<br />
> docs(*): update rtl documention

- en/components/themes/sass/palettes.md
Closes #3177 
<br />
<br />
<br />
> docs(palettes): provide a list of predefined palettes

- en/components/themes/sass/schemas.md
Closes #3178 
<br />
<br />
<br />
> docs(schemas): provide list with predefined schemas

- en/components/grid/groupby.md
- en/components/grids_templates/sorting.md
Closes #3180
<br />
<br />
<br />
> Update grid sort & group topic

- en/components/expansion-panel.md
Related to https://github.com/IgniteUI/igniteui-angular-samples/pull/3010
<br />
<br />
<br />
> docs(expansion-panel): update expansion panel docs

- en/components/general-changelog-dv.md
- en/components/general/update-guide.md
- en/components/slider/slider.md
- en/components/toc.yml
- jp/components/toc.yml
Closes #3209 
<br />
<br />
<br />
> Minor fixes

- package-lock.json
- package.json
Closes #3234 
<br />
<br />
<br />
> upgrade of template version

- en/components/toc.yml
> fixed toc for geo-map

- en/components/general/ignite-ui-licensing.md
- jp/components/general/ignite-ui-licensing.md
Closes #3247 
<br />
<br />
<br />
> Change import to use inside ignite-ui-licensing.md 

- en/components/general/ignite-ui-licensing.md
- jp/components/general/ignite-ui-licensing.md
Closes #3247
<br />
<br />
<br />
> docs: Update ignite-ui-licensing.md - change import to use

- en/components/time-picker.md
Closes # 
<br />
<br />
<br />
> add customizing the toggle and clear icons section to time picker

- en/components/grids_templates/column-hiding.md
- jp/components/grids_templates/column-hiding.md
- kr/components/grids_templates/column-hiding.md
- kr/components/grids_templates/toolbar.md
Closes #2681
<br />
<br />
<br />
> docs: remove deprecated properties and change text accordingly

- en/components/input-group.md
Related to IgniteUI/igniteui-angular-samples/issues/3022
<br />
<br />
<br />
> feat(docs): add typed forms

- en/components/grid/grid.md
Related to https://github.com/IgniteUI/igniteui-docfx/pull/3267
<br />
<br />
<br />
> Update complex binding topic - master

- en/components/date-range-picker.md
- jp/components/date-range-picker.md
Closes #3190 
<br />
<br />
<br />
> Update code snippets for IgxDateRangePicker

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> upgrade to 3.2.0 template version

- en/components/rating.md
- en/components/toc.yml
- jp/components/rating.md
- jp/components/toc.yml
- kr/components/rating.md
- kr/components/toc.yml
Closes #3269  
<br />
<br />
<br />
> docs(rating): adding rating docs.

- en/components/grids_templates/conditional-cell-styling.md
Closes #3131 
<br />
<br />
<br />
> Change height for rowClasses sample container

- en/components/grids_templates/column-types.md
Closes #3293 
<br />
<br />
<br />
> Fix column types meta data vnext

- en/components/grids_templates/column-types.md
Closes #3293 
<br />
<br />
<br />
> Fix column types meta data - master

- package-lock.json
- package.json
> update igniteui-docfx-template version

- package-lock.json
- package.json
Related to #3276
<br />
<br />
<br />
> Update template version - vnext

- en/.gitignore
- en/components/grids_templates/state-persistence.md
- en/components/pivotGrid/pivot-grid.md
- en/components/toc.yml
- en/web.config
- gulpfile.js
- jp/.gitignore
- jp/components/grids_templates/state-persistence.md
- jp/components/pivotgrid/pivot-grid.md
- jp/components/toc.yml
- jp/web.config
- kr/.gitignore
- kr/components/pivotgrid/pivot-grid.md
- kr/web.config
Closes # 
<br />
<br />
<br />
> Add pivot grid state persistence topic. Add jp version.

- en/components/grids_templates/validation.md
Closes #3308 
<br />
<br />
<br />
> docs(validation): fix heights of the samples for validator

- en/components/list.md
- jp/components/list.md
- kr/components/list.md
Closes #3300 
<br />
<br />
<br />
> feat(list): adding item selection to the topic

- en/components/grids_templates/row-actions.md
- jp/components/grids_templates/row-actions.md
Closes #3314
<br />
<br />
<br />
> fix identation and add missing tag

- en/components/general/ignite-ui-licensing.md
- jp/components/general/ignite-ui-licensing.md
Closes #3297
<br />
<br />
<br />
> Licensing update

- en/components/combo.md
- en/components/simple-combo.md
Closes #3328  
<br />
<br />
<br />
> combo/simple combo - add limitation for falsy values

- en/components/simple-combo.md
Closes #3332 
<br />
<br />
<br />
> simple-combo - add limitation when ngModel and required are used

- en/components/pivotGrid/pivot-grid-features.md
Closes #3334 
<br />
<br />
<br />
> feat(pivot-grid): add section about excel export

- jp/components/combo.md
- jp/components/exporter-excel.md
- jp/components/general/localization.md
- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/export-excel.md
- jp/components/pivotgrid/pivot-grid-features.md
- jp/components/query-builder.md
- jp/components/simple-combo.md
Closes # 
<br />
<br />
<br />
> Updating JP content with the latest changes - vNext

- en/components/grids_templates/export-excel.md
- en/components/pivotGrid/pivot-grid-features.md
- en/components/toc.yml
Closes #3342 
<br />
<br />
<br />
> feat(pivot-grid): moved export to separate topic - vNext

- en/components/grids_templates/export-excel.md
- en/components/pivotGrid/pivot-grid-features.md
- en/components/toc.yml
Closes #3342  
<br />
<br />
<br />
> feat(pivot-grid): moved export to separate topic - master

- en/components/rating.md
Closes # 
<br />
<br />
<br />
> docs(rating): updating rating topic  based on seo review - master

- en/components/general/angular-grid-overview-guide.md
- en/components/grids-and-lists.md
- jp/components/general/angular-grid-overview-guide.md
- jp/components/grids-and-lists.md
Closes # 
<br />
<br />
<br />
> Fix CRM not loading problem

- en/components/general/angular-grid-overview-guide.md
- en/components/grids-and-lists.md
- jp/components/general/angular-grid-overview-guide.md
- jp/components/grids-and-lists.md
Closes #3364 
<br />
<br />
<br />
> update grid crm route

- en/components/calendar.md
- jp/components/calendar.md
Closes #3363 
<br />
<br />
<br />
> docs(calendar): update page with new titles and paragraphs - vnext

- package-lock.json
- package.json
Update version of igniteui-docfx-template
<br />
<br />
<br />
> chore(dependencies): update template version - vnext

- en/components/action-strip.md
- en/components/general/how-to/how-to-perform-crud.md
- en/components/grids_templates/row-actions.md
- jp/components/action-strip.md
- jp/components/general/how-to/how-to-perform-crud.md
- jp/components/grids_templates/row-actions.md
- kr/components/action-strip.md
Closes #3385 
<br />
<br />
<br />
> fix(action-strip): apply correct links for pinning and editing actions - vnext

- en/components/action-strip.md
- en/components/general/how-to/how-to-perform-crud.md
- en/components/grids_templates/row-actions.md
- jp/components/action-strip.md
- jp/components/general/how-to/how-to-perform-crud.md
- jp/components/grids_templates/row-actions.md
- kr/components/action-strip.md
Closes #3385 
<br />
<br />
<br />
> fix(action-strip): apply correct links for pinning and editing actions - master

- en/components/general/update-guide.md
- en/components/grids_templates/column-hiding.md
- en/components/grids_templates/toolbar.md
- jp/components/grids_templates/column-hiding.md
- jp/components/grids_templates/toolbar.md
- kr/components/grids_templates/column-hiding.md
- kr/components/grids_templates/toolbar.md
Reflecting changes from https://github.com/IgniteUI/igniteui-angular/pull/12230
<br />
<br />
<br />
> Toolbar title and actions update

- en/components/card.md
- jp/components/card.md
Closes #3400
<br />
<br />
<br />
> chore(*): update card page - vnext

- en/components/carousel.md
- jp/components/carousel.md
Closes #3395 
<br />
<br />
<br />
> chore(*): update carousel page - master

- en/components/paginator.md
- jp/components/paginator.md
Closes https://github.com/IgniteUI/igniteui-docfx/issues/3389
> chore(pagination): improve seo of the page - vNext

- en/components/paginator.md
- jp/components/paginator.md
> chore(pagination): improve seo of the page - master

- en/components/carousel.md
- jp/components/carousel.md
Closes #3395 
<br />
<br />
<br />
> chore(*): update carousel page - vnext

- en/components/pivotGrid/pivot-grid-custom.md
- en/components/pivotGrid/pivot-grid-features.md
- en/components/pivotGrid/pivot-grid.md
- jp/components/pivotgrid/pivot-grid-custom.md
- jp/components/pivotgrid/pivot-grid-features.md
- jp/components/pivotgrid/pivot-grid.md
- kr/components/pivotgrid/pivot-grid-custom.md
- kr/components/pivotgrid/pivot-grid-features.md
- kr/components/pivotgrid/pivot-grid.md
> Fix link for PivotDataSelector component.

- .github/workflows/node.js.yml
- en/components/general-changelog-dv.md
- gulpfile.js
Closes #3394 
<br />
<br />
<br />
> Fail ci build on gulp build warnings

- en/components/paginator.md
> chore(*): resolve conflicts vnext

- en/components/expansion-panel.md
- jp/components/expansion-panel.md
> chore(expansion-panel): update page with seo improvements - master

- en/components/expansion-panel.md
- jp/components/expansion-panel.md
> chore(expansion-panel): update page with seo improvements - vNext

- en/components/pivotGrid/pivot-grid.md
Related to this PR https://github.com/IgniteUI/igniteui-angular/pull/12330
<br />
<br />
<br />
> Add information about newly exposed aggregatorName property

- en/components/grids_templates/column-types.md
- en/components/toc.yml
Note: Also resolving an issue with anchor links not working for `dataType` API docs links.
<br />
<br />
<br />
> feat(image column): updating data types topic

- en/components/stepper.md
- jp/components/stepper.md
Closes #3439 
<br />
<br />
<br />
> fix(stepper): apply the correct link for the W3 accessability standards

- en/components/grids-and-lists.md
- jp/components/grids-and-lists.md
Closes [#3135](https://github.com/IgniteUI/igniteui-angular-samples/issues/3135)
<br />
<br />
<br />
> feat(grids-and-lists): add stackblitz view for crm grid

- en/components/input-group.md
Related to [#3145](https://github.com/IgniteUI/igniteui-angular-samples/issues/3145)
<br />
<br />
<br />
> Change input group description

- en/components/grids_templates/state-persistence.md
- jp/components/grids_templates/state-persistence.md
Closes #3277
<br />
<br />
<br />
> feat(state-persistence): add section for stateParsed event for grid component

- en/components/input-group.md
Closes #3146 
<br />
<br />
<br />
> input-group: add validation section

- en/components/grids_templates/row-drag.md
Closes #3458 
<br />
<br />
<br />
> fix(row-drag-tree-grid-en): edit code snippet

- en/components/grids_templates/row-selection.md
- en/components/grids_templates/selection.md
- jp/components/grids_templates/row-selection.md
- jp/components/grids_templates/selection.md
Closes #3318
<br />
<br />
<br />
> fix(selection): add code snippets for selection events

- jp/components/date-picker.md
- jp/components/date-range-picker.md
- jp/components/date-time-editor.md
- jp/components/drop-down-hierarchical-selection.md
- jp/components/grids_templates/row-drag.md
- jp/components/grids_templates/state-persistence.md
- jp/components/input-group.md
- jp/components/time-picker.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> [Localization] Updating JP content with the latest changes - Input Group, new topic, other fixes.

- en/components/tree.md
Closes #3464 
<br />
<br />
<br />
> IgxTree: Fix the selection section API of the tree topic

- en/components/checkbox.md
- en/components/grids_templates/cell-editing.md
Closes #3452
<br />
<br />
<br />
> Kdragieva/3452 SEO improvements on checkbox help page

- en/components/select.md
Closes #3453
<br />
<br />
<br />
> chore(SEO): improvements on select page

- en/components/button.md
- en/components/grids_templates/row-editing.md
Closes #3449
<br />
<br />
<br />
> chore(SEO): improvements on button page

- en/components/button.md
- en/components/checkbox.md
- en/components/grids_templates/cell-editing.md
- en/components/grids_templates/row-editing.md
- en/components/select.md
reverting changes made by mistake before merging PR#3373
> reverting changes made before merging PR

- en/components/grids-and-lists.md
- package-lock.json
- package.json
Related to #https://github.com/IgniteUI/igniteui-angular-samples/issues/3239 and https://github.com/IgniteUI/igniteui-docfx-template/issues/409
<br />
<br />
<br />
> Update template version

- jp/components/grids-and-lists.md
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/3239
<br />
<br />
<br />
> Update jp grids and lists page

- en/components/general/update-guide.md
- jp/components/general/update-guide.md
> fix: igx for version 14

- en/components/select.md
Closes #3491  
<br />
<br />
<br />
> docs(igx-select): separate code snippets and sections

- en/environment.json
- jp/environment.json
- kr/environment.json
Reverts IgniteUI/igniteui-docfx#3482
> Revert "changing endpoints for theming to codegen service"

- en/components/toc.yml
Closes # 
<br />
<br />
<br />
> feat(theming): forgot to tag as new

- en/components/themes/sass/component-themes.md
- en/components/toc.yml
- en/environment.json
- jp/environment.json
- kr/environment.json
Closes # 
<br />
<br />
<br />
> reverts change that breaks TAAS

- en/components/grids_templates/remote-data-operations.md
- en/components/grids_templates/row-selection.md
- jp/components/grids_templates/remote-data-operations.md
- jp/components/grids_templates/row-selection.md
Closes # 
<br />
<br />
<br />
> add links to api

- en/components/grid/groupby.md
- jp/components/grid/groupby.md
Closes #3545 
<br />
<br />
<br />
> feat(group-by): add snipper for using new group-member-count sorting

- .github/CONTRIBUTING.md
- .github/workflows/node.js.yml
Closes # 
<br />
<br />
<br />
> ci(*): updating contribution md and yml for new branch name

- en/components/themes/sass/configuration.md
- jp/components/themes/sass/configuration.md
Closes #3157
<br />
<br />
<br />
> Update scrollbar styling topic

- en/components/grids_templates/cascading-combos.md
- en/components/simple-combo.md
- en/components/toc.yml
- jp/components/toc.yml
Related issue - https://github.com/IgniteUI/igniteui-angular-samples/issues/3264
Closes #
<br />
<br />
<br />
> Add documentation and sample overview for Grid Cascading Combos

- jp/components/carousel.md
- jp/components/grids_templates/cascading-combos.md
- jp/components/simple-combo.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> [JP] Adding Cascading Combos topic, other changes.

- jp/components/general/update-guide.md
- jp/components/grids_templates/column-hiding.md
- jp/components/grids_templates/summaries.md
- jp/components/grids_templates/toolbar.md
Closes # 
<br />
<br />
<br />
> [JP] Adding the latest topic changes - 15.1 update guide.

- en/components/button.md
Closes #3549  
<br />
<br />
<br />
> docs(igx-button): separate code snippets and sections

- jp/components/general/ignite-ui-licensing.md
Closes # 
<br />
<br />
<br />
> [JP] Updating Licensing topic.

- nuget.config
adding nuget.config so that restore is independent on build agent
> Adding nuget.config so that restore is independent on build agent

- en/components/date-picker.md
- en/components/date-range-picker.md
- en/components/date-time-editor.md
Closes # 
<br />
<br />
<br />
> fix(pickers): improving links and code snippet

- en/components/grids_templates/conditional-cell-styling.md
- jp/components/grids_templates/conditional-cell-styling.md
Closes #3616  
<br />
<br />
<br />
> docs(tree-grid): update rowStyles style definiton code snippet

- jp/components/date-picker.md
- jp/components/date-range-picker.md
- jp/components/date-time-editor.md
- jp/components/grids_templates/sizing.md
Closes # 
<br />
<br />
<br />
> [JP] Adding the latest content changes - Sizing, pickers; other fixes

- en/components/general/how-to/how-to-use-standalone-components.md
- en/components/general/update-guide.md
- en/components/toc.yml
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> docs(ng16): adding info about standalone

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> chore(*): update template version

- en/components/toc.yml
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> docs(how-to): using the new preview label for stanadalone comps

- en/components/general/update-guide.md
Closes #3634 
<br />
<br />
<br />
> Update the Update guide topic

- en/components/general/how-to/how-to-use-standalone-components.md
Closes # 
<br />
<br />
<br />
> feat(standalone): adding directives table

- en/components/grid/grid.md
Closes # 
<br />
<br />
<br />
> chore(*): remove embeded video lazy loading

- en/components/icon.md
Closes #3668 
- [] check topic's TOC/menu and paragraph headings
<br />
<br />
<br />
> feat(icon): add section about material symbols

- en/components/radio-button.md
Closes # 
<br />
<br />
<br />
> chore(*): Increase radio button samples height

- en/components/themes/typography.md
Closes # 
<br />
<br />
<br />
> fix(theme): typography table was not formatted

- en/components/stepper.md
Closes #3813 
<br />
<br />
<br />
> feat(stepper): igxStepSubTitle to  igxStepSubtitle

- en/components/grids_templates/toolbar.md
Closes #2590  
<br />
<br />
<br />
> fix(tree-grid, toolbar): changing frame height of the features toolbar sample

- en/components/select.md
Closes #3828  
<br />
<br />
<br />
> fix(select): displaying the note section properly

- en/components/dialog.md
Closes #3848 
<br />
<br />
<br />
> fix(dialog): displaying the dialog links properly

- en/components/action-strip.md
Closes #3846  
<br />
<br />
<br />
> fix(action-strip): displaying all note sections properly

- en/components/slider/slider-ticks.md
- en/components/slider/slider.md
Closes #3844  
<br />
<br />
<br />
> fix(slider): displaying the slider links properly

- jp/components/action-strip.md
- jp/components/dialog.md
- jp/components/grids_templates/multi-row-layout.md
- jp/components/slider/slider-ticks.md
- jp/components/slider/slider.md
Closes # 
<br />
<br />
<br />
> Adding the latest formatting changes - JA.

- en/components/stepper.md
Closes #3851
<br />
<br />
<br />
> fix(stepper): displaying all note sections properly

- jp/components/stepper.md
Closes # 
<br />
<br />
<br />
> [JA] Fixing NOTE sections as per EN - Stepper topic.

- en/components/date-time-editor.md
Closes #3853  
<br />
<br />
<br />
> fix(date-time-editor): displaing all notes and section title properly

- en/components/accordion.md
- en/components/expansion-panel.md
- en/components/layout.md
Closes #3868  
<br />
<br />
<br />
> fix(accordion, expansion-panel, layout): displaying the note sections properly

- en/components/icon.md
- en/components/linear-progress.md
- en/components/mask.md
Closes #3876  
<br />
<br />
<br />
> fix(icon, linear-progress, mask): displaying the note sections properly

- en/components/button-group.md
- en/components/button.md
- en/components/carousel.md
- en/components/chip.md
- en/components/display-density.md
- en/components/general/how-to/how-to-customize-theme.md
- en/components/general/update-guide.md
- en/components/grid/grid.md
- en/components/grids-and-lists.md
- en/components/grids_templates/conditional-cell-styling.md
- en/components/grids_templates/display-density.md
- en/components/grids_templates/multi-column-headers.md
- en/components/grids_templates/paging.md
- en/components/grids_templates/remote-data-operations.md
- en/components/hierarchicalgrid/hierarchical-grid.md
- en/components/list.md
- en/components/paginator.md
- en/components/toc.yml
- en/components/treegrid/groupby.md
Closes #3875
<br />
<br />
<br />
> Size (Display Density): Reflect changes to sizing in 16.1.x

- en/components/pivotGrid/pivot-grid-custom.md
- en/components/pivotGrid/pivot-grid-features.md
- en/components/pivotGrid/pivot-grid.md
Closes #3897  
<br />
<br />
<br />
> fix(pivot-grid): displaying the note section and the links properly

- jp/components/pivotgrid/pivot-grid-custom.md
- jp/components/pivotgrid/pivot-grid-features.md
- jp/components/pivotgrid/pivot-grid.md
- jp/components/transaction-classes.md
Closes # 
<br />
<br />
<br />
> [JP] Updating Pivot Grid topics - Note sections, other fixes

- en/components/button-group.md
Closes #3893 
<br />
<br />
<br />
> Update button group selection section 

- jp/components/button-group.md
Closes # 
<br />
<br />
<br />
> [JP] Updating Button Group topic with the latest changes

- en/components/grid/groupby.md
- en/components/grids_templates/cell-selection.md
- en/components/grids_templates/column-types.md
- en/components/grids_templates/keyboard-navigation.md
- en/components/grids_templates/row-actions.md
- en/components/grids_templates/row-selection.md
- en/components/grids_templates/sorting.md
- en/components/grids_templates/state-persistence.md
Closes #3914 
<br />
<br />
<br />
> fix(grid): displaying the note sections in the grid topics properly

- en/components/general/how-to/how-to-use-standalone-components.md
Closes # 
<br />
<br />
<br />
> docs(standalone): removing preview for standalone

- en/components/general/localization.md
Closes # 
<br />
<br />
<br />
> feat(i18n): updating topic for igniteui-angular 17

- en/components/general/localization.md
Closes # 
<br />
<br />
<br />
> docs(localization): removing unnecessary stackblitz

- en/components/general/update-guide.md
Related to https://github.com/IgniteUI/igniteui-angular/issues/13668
<br />
<br />
<br />
> Describe additional steps for nguniversal projects that update to 17

- en/components/toc.yml
Closes # 
<br />
<br />
<br />
> chore(*): updating TOC labels

- en/components/toc.yml
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> [JA] Updating TOC labels.

- en/components/avatar.md
- en/components/button.md
- en/components/chip.md
- en/components/icon.md
- en/components/splitter.md
Closes #4022  
<br />
<br />
<br />
> docs(size): add custom sizing section to sizable components

- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> Updating JA TOC to match the latest EN changes

- en/components/general/update-guide.md
- en/components/toc.yml
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> docs(icon-btn): update guide and toc

- jp/components/drop-down-hierarchical-selection.md
- jp/components/drop-down.md
- jp/components/general/how-to/how-to-use-standalone-components.md
- jp/components/slider/slider.md
Closes # 
<br />
<br />
<br />
> docs(*): Updating JA - Dropdown, Standalone, Slider - vnext

- en/components/date-picker.md
Closes #5711 
<br />
<br />
<br />
> fix(date-picker): edit typos in topic

- en/components/grids_templates/toolbar.md
Related to changes from https://github.com/IgniteUI/igniteui-angular/pull/13907
<br />
<br />
<br />
> docs(hgrid): update chid grid simpler toolbar setup w/ 17.1

- en/components/texthighlight.md
- package-lock.json
Closes # 
<br />
<br />
<br />
> feat(text-highlight): updating docs for 17.1

- jp/components/date-picker.md
- jp/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> [JA] Update Guide - 17.1.x, Date Picker fixes

- en/components/calendar.md
- en/components/carousel.md
- en/components/date-picker.md
- en/components/date-range-picker.md
- en/components/grid/grid.md
- en/components/hierarchicalgrid/hierarchical-grid.md
- en/components/list.md
- en/components/month-picker.md
- en/components/navdrawer.md
- en/components/slider/slider.md
- en/components/time-picker.md
- en/components/treegrid/tree-grid.md
Closes # 
<br />
<br />
<br />
> Add additional information about hammer being optional now.

- jp/components/calendar.md
- jp/components/carousel.md
- jp/components/date-picker.md
- jp/components/date-range-picker.md
- jp/components/grid/grid.md
- jp/components/grids_templates/toolbar.md
- jp/components/hierarchicalgrid/hierarchical-grid.md
- jp/components/list.md
- jp/components/month-picker.md
- jp/components/navdrawer.md
- jp/components/slider/slider.md
- jp/components/spreadsheet_overview.md
- jp/components/texthighlight.md
- jp/components/time-picker.md
- jp/components/treegrid/tree-grid.md
Closes # 
<br />
<br />
<br />
> [JA] Updating Toolbar and Text Highlight with the latest changes

- en/components/general/update-guide.md
Related to IgniteUI/igniteui-angular/issues/13957
<br />
<br />
<br />
> fix(update-guide): update icon btn info

- jp/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> [JA] Update Guide - Icon Button section

- en/components/grids_templates/conditional-cell-styling.md
Closes #5712 
<br />
<br />
<br />
> Refactor tree & hierarchical grid conditional styling snippets

- jp/components/grids_templates/conditional-cell-styling.md
Closes # 
<br />
<br />
<br />
> [JA] Updating conditional styling snippets to match EN topic

- en/components/general/getting-started.md
- en/components/general/update-guide.md
Closes #5715 
<br />
<br />
<br />
> docs(theming): update sections for igniteui-theming

- jp/components/general/getting-started.md
- jp/components/general/update-guide.md
Closes # 
<br />
<br />
<br />
> [JA] docs(*): Updating Getting Started + Update Guide

- en/components/slider/slider.md
Closes # 5765
<br />
<br />
<br />
> Correcting links for API documentation of Slider

- en/components/general/getting-started.md
- en/components/general/update-guide.md
- en/components/slider/slider.md
- en/components/splitter.md
- jp/components/radial-gauge.md
Closes # 
<br />
<br />
<br />
> Fixing merge conflicts with master

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> chore(*): Update cta banners

- en/components/card.md
Closes #5808
<br />
<br />
<br />
> fix(card): remove reverse docs

- en/components/charts/chart-overview.md
- en/components/grid/grid.md
- jp/components/charts/chart-overview.md
- jp/components/grid/grid.md
- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> chore(*): update code views static images

- en/components/stepper.md
Closes # 
<br />
<br />
<br />
> feat(angular): adding angular reactive forms stepper sample

- en/components/general/update-guide.md
- en/components/grids_templates/export-excel.md
- en/components/grids_templates/state-persistence.md
- en/components/pivotGrid/pivot-grid-features.md
- en/components/pivotGrid/pivot-grid.md
Closes # 
<br />
<br />
<br />
> docs(pivot-grid): Update docs with the new pivot features

- en/components/grids_templates/paging.md
Related to IgniteUI/igniteui-angular-samples/issues/3473
<br />
<br />
<br />
> docs(grid): fix outdated section

- jp/components/button-group.md
- jp/components/button.md
- jp/components/card.md
- jp/components/display-density.md
- jp/components/general/how-to/how-to-customize-theme.md
- jp/components/grids-and-lists.md
- jp/components/grids_templates/conditional-cell-styling.md
- jp/components/grids_templates/sizing.md
- jp/components/grids_templates/summaries.md
- jp/components/pivotgrid/pivot-grid-features.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> docs(*): Updating Card, Sizing topics - JA.

- jp/components/grids_templates/row-selection.md
- jp/components/overlay-position.md
- jp/components/pivotgrid/pivot-grid.md
- jp/components/toggle.md
Closes # 
<br />
<br />
<br />
> docs(*): Updating JA for #5836, other updates.

- en/components/toc.yml
Closes # 
<br />
<br />
<br />
> Remove old new/updated labels. Mark pivot grid  topics as updated.

- jp/components/general/update-guide.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> Updating Japanese TOC + 18.0.x Update Guide

- en/components/grids_templates/sorting.md
Closes #5839  
<br />
<br />
<br />
> docs(sorting): fix initial sorting expressions

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> chore(*): update template with dv samples correct git paths

- en/components/mask.md
Closes #5868 
<br />
<br />
<br />
> docs(mask): update code snippets for focus and blur formatting behavior

- jp/components/general-changelog-dv.md
- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/column-hiding.md
- jp/components/grids_templates/sorting.md
- jp/components/mask.md
Closes # 
<br />
<br />
<br />
> [Localization] Updating JA to match the latest EN changes - DV Changelog, other fixes.

- package-lock.json
- package.json
Closes # 
<br />
<br />
<br />
> chore(*): use cross-env for setting environment variables

- en/components/pivotGrid/pivot-grid-features.md
Closes #5870 
<br />
<br />
<br />
> docs(pivotGrid): added row layout to features

- jp/components/icon-service.md
- jp/components/icon.md
- jp/components/pivotgrid/pivot-grid-features.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> [JA] Icon Service topic, other updates

- en/components/icon-service.md
Closes # 
<br />
<br />
<br />
> refactor(icon-service): update icon references and usage

- en/components/pivotGrid/pivot-grid-features.md
Closes # 
<br />
<br />
<br />
> Updating prod with changes from staging

- en/components/badge.md
Closes # 
<br />
<br />
<br />
> refactor(badge): add --size clarification

- en/components/grids_templates/summaries.md
Closes #6002 
<br />
<br />
<br />
> docs(summaries): enhance summaries topics with disabledSummaries examples

- jp/components/date-picker.md
- jp/components/date-range-picker.md
- jp/components/date-time-editor.md
- jp/components/general/how-to/how-to-use-standalone-components.md
- jp/components/grids_templates/editing.md
- jp/components/time-picker.md
Closes # 
<br />
<br />
<br />
> Update JA topics to match the latest EN updates

- jp/components/carousel.md
- jp/components/snackbar.md
- jp/components/toast.md
Closes # 
<br />
<br />
<br />
> [Localization] Updating Carousel topic - master

- en/components/combo.md
- jp/components/combo.md
Closes #6005  
<br />
<br />
<br />
> docs(combo): update single selection code snippet

- en/components/general/ssr-rendering.md
Closes #6000  
<br />
<br />
<br />
> docs(ssr): Update angular SSR topic

- en/components/carousel.md
Closes #6079  
Align with WC [Carousel Configuration](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/layouts/carousel#carousel-configuration) section.
<br />
<br />
<br />
> docs(carousel): align configuration section with WC

- en/components/query-builder.md
Closes # 
<br />
<br />
<br />
> docs(query-builder): change QB overview sample

- jp/components/carousel.md
Closes # 
<br />
<br />
<br />
> [JA] Update Carousel topic

- en/components/tile-manager.md
- en/components/toc.yml
- jp/components/toc.yml
- package-lock.json
Closes # 
<br />
<br />
<br />
> feat(*): Add Tile Manager topic

- jp/components/query-builder.md
Closes # 
<br />
<br />
<br />
> [JA] Query Builder topic - update sample

- en/components/list.md
- en/components/themes/palettes.md
Same changes as master PR: #6081
> docs(list): update list documentation with the new "selected" property (vnext)

- jp/components/list.md
- jp/components/query-builder-model.md
- jp/components/themes/palettes.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> JA - Query Builder Model topic, List topic updates

- en/components/circular-progress.md
Closes #6085 
<br />
<br />
<br />
> docs(circular-progress): update theme parameter names

- en/components/circular-progress.md
Same changes as master PR: #6097 
<br />
<br />
<br />
> docs(circular-progress): update theme parameter names (vnext)

- jp/components/circular-progress.md
- jp/components/themes/misc/angular-material-theming.md
- jp/components/themes/palettes.md
Closes # 
<br />
<br />
<br />
> [JA] Update Circular Progress topic - theme parameter names + Contrast color docs - master

- en/components/grids_templates/advanced-filtering.md
- en/components/hierarchicalgrid/load-on-demand.md
- en/components/toc.yml
Closes # 
<br />
<br />
<br />
> feat(h-grid): update topics for advanced filtering with subqueries

- jp/components/grids_templates/advanced-filtering.md
- jp/components/hierarchicalgrid/load-on-demand.md
- jp/components/toc.yml
Closes # 
<br />
<br />
<br />
> [JA] Updating topics with the latest changes (advanced filtering with subqueries)

- en/components/button.md
Closes #6106 
<br />
<br />
<br />
> docs(button): add themes for individual button types to the styling section

- jp/components/icon.md
Closes # 
<br />
<br />
<br />
> [JA] Icon - add SVG color limitations - vnext

- jp/components/grids_templates/advanced-filtering.md
- jp/components/grids_templates/excel-style-filtering.md
Closes # 
<br />
<br />
<br />
> docs(grid): JA - update advanced & excel filtering topics (vnext)
