IgniteUI/igniteui-docfx

docfx_project/components/checkbox.md
docfx_project/components/icon.md
docfx_project/components/input.md
docfx_project/components/label.md
docfx_project/components/list.md
docfx_project/components/navbar.md
docfx_project/components/radio_button.md
docfx_project/components/switch.md

Samples for Input, Label, Checkbox, Switch, Radio, Icon and List.

Embedded plunker samples

---

docfx_project/components/grid.md

Update the igxGrid topic

---

.vscode/settings.json
docfx_project/.gitignore
docfx_project/components/button.md
docfx_project/components/grid.md
docfx_project/components/ripple.md

Update Button and Ripple docs

---

docfx_project/components/grid.md

Updated the topic on how to bind the grid to a remote data service.

---

docfx_project/components/grid.md

Copy-editing for the grid document

---

en/components/grid.md
jp/components/grid.md

Fix typo in grid descr

---

jp/components/calendar.md
jp/components/date_picker.md
jp/components/snackbar.md

I fixed full width spaces in headers that should have been half-width spaces.  This should remove the indentation of some headers.
I also removed the backslashes from some type specifications as explained in #42.

Fixed full-width spaces and backslashes

---

templates/ignite-ui-template/styles/docfx.js

Feature: Update the url on sideaffix article location click.

---

templates/ignite-ui-template/styles/css/main.css
templates/ignite-ui-template/styles/sass/partials/_affix.scss

Change: Hover color for sideaffix category items.

---

en/components/slider.md

Reworked angular slider topic

---

jp/components/slider.md

Redoing #89 to target master instead of the topic branch, as it was already merged.

Retranslated slider topic

---

en/components/button.md
en/components/icon.md

Closes #100
Icon samples rework

Icon samples rework

---

en/components/button.md

Task #84
Creating new pull request, because the old one could not be reopened. The old one is #92.

Reworking Button samples.

---

en/components/toggle.md
jp/components/toggle.md

add some additional descriptions, demos and stackblitz buttons

add samples and stackblitz button to toggle topic

---

en/components/badge.md

Updated badge topic with latest control changes

---

en/components/avatar.md
en/components/badge.md
en/components/card.md
en/components/carousel.md
en/components/icon.md
en/components/navbar.md
jp/components/card.md
jp/components/carousel.md
jp/components/slider.md

add missing iframe and stackblitz details

---

en/components/label_input.md
jp/components/label_input.md

closes IgniteUI/igniteui-angular-samples#75

Add stackblitz button to label-input demo

---

jp/components/badge.md
jp/components/button.md
jp/components/carousel.md
jp/components/checkbox.md
jp/components/icon.md
jp/components/label_input.md
jp/components/navbar.md
jp/components/navdrawer.md
jp/components/radio_button.md
jp/components/slider.md
jp/components/switch.md
jp/components/toggle.md

Added reviewed topics from various rewrites.  These were based on pull requests that were assigned to me.
Additionally, I went through the history of the EN folder to try to get anything that was done without any assignment for localization (and therefore no notification).  This includes some updates for StackBlitz demos.

Eaa rewritten topics

---

en/components/for_of.md
en/components/toc.yml
jp/components/for_of.md
jp/components/toc.yml

Related https://github.com/IgniteUI/igniteui-angular/issues/552

Add igxForOf topic

---

jp/components/calendar.md
jp/components/card.md
jp/components/circular_progress.md
jp/components/date_picker.md
jp/components/dialog.md
jp/components/grid.md
jp/components/layout.md
jp/components/linear_progress.md
jp/components/list.md
jp/components/navdrawer.md
jp/components/scrollbar.md
jp/components/snackbar.md
jp/components/toast.md

Translated StackBlitz button text in topics that were not recently rewritten.
Also removed one header level in a topic for consistency (it didn't look good).

Mostly StackBlitz button translations

---

en/components/list.md
jp/components/list.md

Updating documentation API for igx-list and igx-list-item and adding a new sample for igxEmptyList directive.
#117

Updating API and adding empty list template sample for igx-list.

---

jp/components/avatar.md

Rewritten Avatar topic

---

en/components/badge.md
en/components/slider.md
en/components/snackbar.md

Reworked snackbar topic

---

en/components/navdrawer.md
en/components/toggle.md
templates/ignite-ui-template/styles/css/main.css
templates/ignite-ui-template/styles/sass/partials/_button-link.scss

Related samples PR https://github.com/IgniteUI/igniteui-angular-samples/pull/89
@simeonoff Just FYI, I've added a rule for inline code links

Update Navigation Drawer topic

---

en/components/buttonGroup.md
en/components/ripple.md
en/components/toc.yml

Adding Button Group Samples.

---

en/components/navdrawer.md

based on [commends from the initial PR](https://github.com/IgniteUI/igniteui-docfx/pull/139#pullrequestreview-98610647)

Nav drawer topic feedback fixes

---

en/components/dialog.md
en/components/toc.yml
jp/components/dialog.md

Refactor dialog topic and add api summary

---

en/components/snackbar.md
en/components/toast.md

Toast topic reworked

---

en/components/calendar.md
jp/components/calendar.md

Create igx-calendar user story and update current topic

---

en/components/tabbar.md
jp/components/tabbar.md

Updating the TabBar demo page

---

en/components/buttonGroup.md

Fixing lexicographical errors.

---

en/components/avatar.md

The main demo on the top should be enough. 
#71

Remove unnecessary stackblitz buttons.

---

en/components/calendar.md
en/components/carousel.md

All API methods/properties/events in the calendar and carousel topics are now highlighted for better readability.
Closes #118

`formatOptions`, `formatViews` methods from 5.2 version highlighted in the topic

---

en/components/tabbar.md
jp/components/tabbar.md

Adding border to the sample containers.

---

jp/components/calendar.md

highlight api methods in calendar jp topic

highlight api methods

---

jp/components/avatar.md
jp/components/carousel.md

Removed StackBlitz buttons that were removed in English.  Changed some keywords to use backticks instead of bold formatting, as the same was done in English.

Made changes that did not involve translation

---

en/components/calendar.md
jp/components/calendar.md

Fix broken links and typos in calendar topic

---

en/components/list.md
en/components/tabbar.md

Fixing typos for list and tabbar.

---

jp/components/circular_progress.md
jp/components/dialog.md
jp/components/label_input.md
jp/components/linear_progress.md
jp/components/toggle.md
templates/ignite-ui-template/conceptual.html.primary.js
templates/ignite-ui-template/partials/footer.tmpl.partial
templates/ignite-ui-template/partials/infrafoot.ja.tmpl.partial
templates/ignite-ui-template/partials/infrafoot.tmpl.partial
templates/ignite-ui-template/partials/infranav.ja.tmpl.partial
templates/ignite-ui-template/partials/infranav.tmpl.partial
templates/ignite-ui-template/partials/navbar.tmpl.partial

Added Japanese header & footer

---

en/components/calendar.md
jp/components/calendar.md

Fix calendar samples height, related to https://github.com/IgniteUI/igniteui-angular-samples/issues/103

Fix calendar samples height

---

en/components/button.md
en/components/buttonGroup.md

Fixing button samples Typos.

---

en/components/toast.md

Fixed typos in toast topic

---

en/components/grid.md
jp/components/grid.md
templates/ignite-ui-template/styles/css/main.css
templates/ignite-ui-template/styles/stackblitz-handler.js

Fixed StackBlitz buttons pop-up warning

---

en/components/calendar.md
en/components/carousel.md
en/components/list.md
en/components/tabbar.md
en/components/toggle.md
jp/components/calendar.md
jp/components/carousel.md
jp/components/list.md
jp/components/tabbar.md
jp/components/toggle.md

Close [694](https://github.com/IgniteUI/igniteui-angular/issues/694)

Removed warning for peerDependency on hammerjs

---

jp/toc.yml

Translated subheader

---

en/components/themes.md
templates/ignite-ui-template/styles/docfx.js

fix(navigation): Prefix and suffix navigation not showing in IE11

---

jp/components/badge.md
jp/components/calendar.md
jp/components/card.md
jp/components/dialog.md
jp/components/grid.md
jp/components/list.md
jp/components/navbar.md
jp/components/navdrawer.md
jp/components/tabbar.md

1. Changed internal anchors to use Japanese text where applicable (so they work).
2. Changed production URLs to be relative (so they work on staging too).
3. Added rewritten NavBar topic.

Mostly link fixes

---

en/components/calendar.md

fix typos in calendar topic

---

jp/components/themes.md

Added default palette

---

en/components/calendar.md
jp/components/calendar.md

Update description of formatViews property

---

en/components/mask.md
en/components/switch.md
en/components/toc.yml
jp/components/mask.md
jp/components/toc.yml

Added topic for mask directive

---

en/components/time_picker.md
en/components/toc.yml
jp/components/time_picker.md
jp/components/toc.yml

Add samples for timepicker

---

en/components/grid.md
en/components/grid_virtualization.md
en/components/toc.yml
jp/components/grid_virtualization.md
jp/components/toc.yml

Adding "Grid Virtualization and Performance" subtopic.

---

en/components/icon.md

I'm intuiting these changes are necessary, but am not 100% certain so please verify.

igx-icon API discrepencies

---

jp/components/icon.md

I saw that a pull request was closed which made this change.  So I'm making it in Japanese too.

Bug fix from John

---

en/components/for_of.md
jp/components/for_of.md

igxFor docs changes for smooth scrolling improvement

---

en/components/grid.md
jp/components/grid.md

Closes IgniteUI/igniteui-angular#963

Add description for igxGrid's onContextMenu output

---

en/components/grid_summaries.md
jp/components/grid_summaries.md

[Summary](https://github.com/IgniteUI/igniteui-angular-samples/issues/139)

Added summary sample to grid-summary topic

---

en/components/toc.yml

Fixes broken build because of a bad toc.yml file formatting.

---

en/components/grid_filtering.md
en/components/grid_paging.md

Add samples to the grid giltering/paging topics

---

en/components/grid_filtering.md
en/components/grid_paging.md
en/components/grid_summaries.md
jp/components/grid_filtering.md
jp/components/grid_paging.md
jp/components/grid_summaries.md

Close #282 
@ig-ealbert we need to merge this by the end of the day, I am going to write you an email in order to keep track of this PR after the merge.
I have added samples and summaries description in the JP files.

fix(docs): Changing demos position and updating Summary description

---

en/components/tabs.md
en/components/toc.yml
jp/components/tabs.md
jp/components/toc.yml

docs(tabs): Added documentation for tabs #274

---

templates/ignite-ui-template/styles/stackblitz-handler.js

fix(SB samples): Assets URL broken after clicking more than once on the SB buttons

---

en/components/grid_column_resizing.md

Add sample for column resizing

Add sample for column resizing

---

en/components/grid_sorting.md
jp/components/grid_sorting.md

Closes IgniteUI/igniteui-angular-samples#204

Add sample for sorting

---

README.md

Documented chocolaye's elevated permissions security requirment.

---

.github/CONTRIBUTING.md

Close #302 
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/130

improvement(contributing.md): Updating contribution file

---

en/components/grid_selection.md

Fix selection sample SB  button

---

en/components/grid.md

fix(doc): Removing onCellSelection event

---

en/components/grid_filtering.md
en/components/grid_sorting.md
en/components/grid_summaries.md

fix(docs): Change notes position

---

en/components/grid_selection.md

Related to https://github.com/IgniteUI/igniteui-angular-samples/pull/236
Adjust sizing of grid selection sample container

Remove whitespaces in grid selection sample

---

en/components/grid.md
en/components/grid_column_pinning.md
en/components/grid_column_resizing.md
en/components/grid_filtering.md
en/components/grid_paging.md
en/components/grid_selection.md
en/components/grid_sorting.md
en/components/grid_summaries.md
en/components/grid_virtualization.md
en/components/toc.yml
jp/components/grid.md
jp/components/grid_column_pinning.md
jp/components/grid_column_resizing.md
jp/components/grid_filtering.md
jp/components/grid_paging.md
jp/components/grid_selection.md
jp/components/grid_sorting.md
jp/components/grid_summaries.md
jp/components/grid_virtualization.md

Fixed grid demos

---

en/components/grid_selection.md
en/components/grid_summaries.md
jp/components/grid_selection.md
jp/components/grid_summaries.md

remove blank space under grid demos

---

en/components/toc.yml
jp/components/toc.yml
templates/ignite-ui-template/partials/li.tmpl.partial

Fixed menu to render children when we have a parent with tag new

---

en/components/categorychart.md
en/components/categorychart_configuration_options.md
en/components/categorychart_explore_chart_types.md
en/components/financialchart.md
en/components/financialchart_configuration_options.md
en/components/financialchart_custom_indicators.md
en/components/financialchart_explore_chart_types.md
en/components/financialchart_panes.md
en/components/financialchart_performance.md

Closes #342, Closes #340, Closes #339, Closes #338, Closes #336, Closes #335, Closes #333, Closes #332, Closes #330

fixed several issues in FC/CC topics

---

en/components/grid_column_pinning.md
en/components/grid_virtualization.md

docs(igxGrid): adding limitations #347 #348

---

en/components/grid_column_pinning.md
en/components/grid_filtering.md
en/components/grid_paging.md
en/components/grid_selection.md
en/components/grid_sorting.md
en/components/grid_summaries.md
en/components/grid_virtualization.md
jp/components/grid_column_pinning.md
jp/components/grid_filtering.md
jp/components/grid_paging.md
jp/components/grid_selection.md
jp/components/grid_sorting.md
jp/components/grid_summaries.md
jp/components/grid_virtualization.md

Closes IgniteUI/igniteui-angular-samples#264

Enhance some of the grid samples 

---

templates/ignite-ui-template/styles/css/main.css
templates/ignite-ui-template/styles/docfx.css
templates/ignite-ui-template/styles/sass/partials/_toc.scss

fix(demos): mobile nav items not displayed correctly

---

jp/components/tabs.md

Fixes #370.  Hopefully.
Note: This is not critical.  We do not need this for the 18.1 release.  We have a build that we can promote to production for marketing release.

Added language metadata field

---

jp/components/grid_column_pinning.md
jp/components/grid_column_resizing.md

Added StackBlitz button translations

---

en/components/grid_filtering.md
en/components/grid_sorting.md
jp/components/grid_filtering.md
jp/components/grid_sorting.md

Add explanation that additional changes should be made, on application level, for features like sorting and filtering, when it comes to using of `string` values on `Date` column.
Close #377

Update grid topics for date object usage

---

en/components/input_group.md
jp/components/input_group.md

Update snippets to import IgxInputGroupModule

---

en/components/grid.md
jp/components/grid.md

Related to [1201](https://github.com/IgniteUI/igniteui-angular/issues/1201) issue.

chore(igxGrid): add desc about newly exposed dblclick evt

---

package.json

Commit new docfx-template 1.0.1 version

---

jp/components/card.md

Update card sample iframe height

---

en/docfx.json
en/global.json
jp/docfx.json
jp/global.json
package-lock.json
package.json

Closes https://github.com/IgniteUI/igniteui-docfx/issues/422. Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/362.

Updated Ignite UI DocFX template version to 1.0.4

---

en/components/toc.yml
jp/components/toc.yml

Exclude drop-down component from table of contents untill it is released.

Exclude drop-down component from docs

---

en/components/card.md
jp/components/card.md

Updating names in card doc
Closes #430

Updating names in card doc

---

en/components/icon.md
jp/components/icon.md

Adding description for content projection

---

en/components/exporter_csv.md
en/components/exporter_excel.md
jp/components/exporter_csv.md
jp/components/exporter_excel.md

#397
fix(exporters): adding a note regarding the JSZip dependency of the exporters

fix(exporters): adding a note regarding JSZip

---

en/components/grid_multi_column_headers.md
en/components/toc.yml
jp/components/grid_multi_column_headers.md
jp/components/toc.yml

chore(igxGrid): create multi column headers topic #460

---

en/components/grid.md
jp/components/grid.md

Adding new known issue related to min allowed col widths.

Adding new known issue related to min allowed col widths.

---

en/components/grid.md
en/components/grid_filtering.md
jp/components/grid.md
jp/components/grid_filtering.md

Related to IgniteUI/igniteui-angular#1355

docs(grid): Updated docs for filtering with latest changes #1355

---

en/components/toc.yml
jp/components/toc.yml

chore: Uncomment dropdown samples from TOC.

---

en/components/grid_multi_column_headers.md
jp/components/grid_multi_column_headers.md

Column group topic

---

en/components/grid_virtualization.md
en/components/radio_button.md
en/components/toc.yml
jp/components/grid_virtualization.md
jp/components/radio_button.md
jp/components/toc.yml

Related to IgniteUI/igniteui-angular#1676

docs(radio-group): Added info about new radio-group

---

en/components/overlay_main.md
en/components/overlay_position.md
en/components/overlay_scroll.md
en/components/toc.yml
jp/components/overlay_main.md
jp/components/overlay_position.md
jp/components/overlay_scroll.md
jp/components/toc.yml

IgxOverlay Topic

---

en/components/combo.md
jp/components/combo.md
jp/components/grid_groupby.md

Reverts IgniteUI/igniteui-docfx#494

Revert "docs(combo): Fixing combo samples dimensions"

---

jp/components/combo.md
jp/components/toc.yml

We try to keep the control names (not feature names) in English.
Fixed a copy/paste issue.
Added new lines to ensure proper formatting.

Fixed combo topic and TOC

---

en/components/toc.yml
jp/components/toc.yml

Related to IgniteUI/igniteui-angular#1610

docs(radio-group): Added tag 'new' to the radio-group demo.

---

jp/components/grid_multi_column_headers.md

Fixed headers and added language metadata

---

en/components/grid_toolbar.md
jp/components/grid_toolbar.md

- adding information regarding column hiding and column pinning
- adding information regarding the "dropDownsMaxHeight" property
- fixing a typo

docs(toolbar): adding information regarding column hiding and pinning

---

en/components/grid.md
jp/components/grid.md

IgniteUI/igniteui-angular#1773

Add all operand to boolean operands

---

en/components/list.md
jp/components/list.md

docs(list): adding info regarding the loading template

docs(list): adding info regarding the loading template

---

en/components/overlay_main.md
en/components/overlay_position.md
en/components/overlay_scroll.md
jp/components/overlay_main.md

Refactor articles (headers), add code snippets, add more sample anchors

IgxOverlay topics refactor

---

en/components/grid.md
en/components/grid_sorting.md
jp/components/grid.md
jp/components/grid_sorting.md

docs(grid): Changing sort method due to a breaking change.

---

en/components/overlay_main.md
en/components/overlay_position.md
en/components/overlay_scroll.md
jp/components/overlay_main.md
jp/components/overlay_position.md

Fixes:
- Examples for component target in overlay_main.md
- Target in API tables in main and position articles
- Swap samples in Scroll article - ScrollStrat is first, Modal is second
- Scroll Strategy code snippet

IgxOverlayTopic update

---

en/components/grid.md
en/components/grid_editing.md
jp/components/grid.md
jp/components/grid_editing.md

Updated grid and grid-editing topic according changes related with PK

---

en/components/combo.md
en/components/drop_down.md
jp/components/combo.md

Fixed typos in the combo and drop-down components.

---

en/components/combo.md
jp/components/combo.md

Add filterable input

---

jp/components/drop_down.md

Closes #542 
Adjust height on JP drop-down sample to mirror EN setup

Drop down JP sample height adjust

---

en/components/list.md

Adding "dataLoadingTemplate" and "isLoading" to API summary
Closes #547.

Adding properties to IgxList's API summary

---

en/components/grid.md

Adding grouping APIs to grid doc.

---

jp/components/overlay_position.md
jp/components/overlay_scroll.md

Checked the topics on staging and made updates to hopefully fix layout issues.

Fixed overlay topics

---

en/components/tabbar.md
en/components/tabs.md
en/components/time_picker.md
jp/components/tabbar.md
jp/components/tabs.md
jp/components/time_picker.md

docs(tabbar): Updated disabled property in some controls topics

---

.github/CONTRIBUTING.md

Add Issue and PR workflow missing statuses

Add missing statuses

---

en/components/grid.md
en/components/grid_displayDensity.md
en/components/toc.yml
jp/components/grid.md
jp/components/grid_displayDensity.md
jp/components/toc.yml

Grid Display Density Topic

---

en/components/mask.md
en/components/radio_button.md
jp/components/mask.md
jp/components/radio_button.md

Closes IgniteUI/igniteui-angular-samples#536 and  IgniteUI/igniteui-angular-samples#535

docs(mask): Fixed cut off sample #536

---

en/components/bulletgraph.md
en/components/lineargauge.md
en/components/radialgauge.md

- changed links to embedded gauge samples
- combined 2 sections about Comparative Measures (performance/target values)
- moved info about animation to top of topic b/c samples are there
- added more content that was missing (e.g. scale in linear gauge and bullet graph)
- embedded a sample for each section/feature
- corrected code snippets to match with samples

Updated Gauge Topics

---

jp/components/bulletgraph.md
jp/components/lineargauge.md
jp/components/radialgauge.md

#565 
Note that some content was removed in English.  I'm matching those changes, assuming it was intentional.

Matched changes from PR 565

---

en/components/grid_column_hiding.md
jp/components/grid_column_hiding.md

fix(columnHiding): update displayOrder section and code-snippets #572

---

jp/components/grid.md
jp/components/grid_displayDensity.md
jp/components/toc.yml

Added new property and new topic related to grid display density.

Grid display density

---

en/components/bulletgraph.md
en/components/lineargauge.md
en/components/radialgauge.md

Added summary with combined code snippets at the end of gauge topics

Added summary to gauge topics

---

en/components/combo.md
jp/components/combo.md

Add back combo remote paragraph

---

en/components/input_group.md
jp/components/input_group.md

The [Input Group Demo](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/input_group.html) sample button is cut off

fix(input-group): Fixed cut off sample

---

en/components/grids_and_lists.md
jp/components/grids_and_lists.md

Updated topic page with all of the new Grid features released since the last time page was released.

Updated content features in Grids and Lists topic

---

en/components/grid.md
en/components/grid_displayDensity.md
en/components/grid_summaries.md
jp/components/grid.md
jp/components/grid_displayDensity.md
jp/components/grid_summaries.md

Grid density and summary topic updates

---

en/components/combo.md
jp/components/combo.md

Add back combo remote paragraph 

---

jp/components/grids_and_lists.md

* Fixed HTML formatting
* Translated an English sentence
* Added a space between English and Japanese text
Fixes #591 (completes fix).

Fixed landing page

---

package-lock.json
package.json

Updated IgniteUI docfx template to 1.0.12.

---

en/components/combo.md
jp/components/combo.md

Combo - API - Rename open/close output events

---

en/components/combo.md
jp/components/combo.md

Combo - API - Rename open/close output events - 6.1.x

---

en/components/grid_paging.md
jp/components/grid_paging.md

docs(grid-paging): add more descriptions about grid remote paging

---

en/components/grid_paging.md
jp/components/grid_paging.md

docs(grid-paging): fix some typos into grid paging topic

---

en/components/tabs.md
jp/components/tabs.md

Related to IgniteUI/igniteui-angular#2253

Move selected index to be Input, 

---

en/components/date_picker.md
en/components/tabbar.md
en/components/tabs.md
en/components/time_picker.md
jp/components/date_picker.md
jp/components/tabbar.md
jp/components/tabs.md
jp/components/time_picker.md

Rename disabled property

---

en/components/chip.md
jp/components/chip.md

Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/562.

fix(chip): Fix button not visible iframe

---

en/components/drop_down.md
jp/components/drop_down.md

Removed redundant code snippet and comment on the DropDown docfx topic.

---

en/components/combo_cascading.md
en/components/combo_features.md
en/components/combo_remote.md
en/components/combo_templates.md
en/components/input_group.md
en/components/input_group_reactive_forms.md
en/components/toc.yml
jp/components/combo.md
jp/components/combo_cascading.md
jp/components/combo_features.md
jp/components/combo_remote.md
jp/components/combo_templates.md
jp/components/input_group.md
jp/components/input_group_reactive_forms.md
jp/components/toc.yml

Closes #568 
Closes #598 
Split combo topics into 5 topics:
- Combo
- Remote Binding
- Features
- Templates
- Cascading Scenario
Add new topic for Reactive Forms integration

Split combo topics and add reactive form topic

---

en/components/circular_progress.md
jp/components/circular_progress.md

update circular bar topic

---

en/components/grid_search.md
jp/components/grid_search.md

Add exactMatch option to gridSearch topic
IgniteUI/igniteui-angular#2369

Add exactMatch option to gridSearch topic

---

en/images/loading.svg
jp/images/loading.svg
package-lock.json

The loading animation indicators now use the #09f color.

refactor(loading): update loading animation to match the new colors

---

en/components/overlay_main.md
en/components/toggle.md
jp/components/overlay_main.md
jp/components/toggle.md

Add docs for `overlaySettings.outlet` added in[ this PR.](https://github.com/IgniteUI/igniteui-angular/pull/2363)
Sections added to Toggle + Overlay

Overlay - API - Include IgxOverlay Outlet in API section

---

en/components/grids_and_lists.md
en/toc.yml
jp/components/grids_and_lists.md

Updated trial link to point to "https://www.infragistics.com/products/ignite-ui-angular/download" within en/toc.yml and en/components/grids_and_lists.tmpl. Also made some other minor content changes to grids and lists overview topic.
**Please note**: for localization only, do not change the free trial link for JP until @DaizenIG confirms that this will be used for that instance.

Content Updates to TOC and Grid Overview Topic

---

en/components/tabs.md
jp/components/tabs.md

Related to IgniteUI/igniteui-angular#1957

docs(tabs): Added info about tabs and routing #1957

---

en/components/tabs.md
jp/components/tabs.md

Related to IgniteUI/igniteui-angular#1957

docs(tabs): Fixed stackbliz links #1957

---

en/components/themes/theming-demo.md
en/components/toc.yml

The topic includes instructions with samples on how to define and  apply themes for Ignite UI for Angular components.
Closes #669.

Providing Theming topic

---

en/components/tabs.md
jp/components/tabs.md

Related to IgniteUI/igniteui-angular-samples#628

docs(tabs): Updated code snippet in en and jp topic #628

---

en/components/grid_virtualization.md
jp/components/grid_virtualization.md

Related to IgniteUI/igniteui-angular-samples#627

docs(grid): Code snippets updated #627

---

en/components/categorychart.md

fix category chart Import

---

jp/components/categorychart.md

#679 
I had marked this as localization-pending, and I think this change should be made before removing that label.  Unless this change in English was wrong?

Fixed import statement as per #679

---

en/components/grid_paging.md
jp/components/grid_paging.md

Update grid paging topic for remote paging

---

en/components/overlay_main.md

onAnimation event added.
Also update in Assumptions and Limitations section was added.

onAnimation event added in igxOverlay

---

en/components/grid_conditional_cell_styling.md
en/components/toc.yml
jp/components/grid_conditional_cell_styling.md
jp/components/toc.yml

Related to IgniteUI/igniteui-angular#1079

docs(grid): Conditional cell styling topic #1079

---

.github/CONTRIBUTING.md

Update CONTRIBUTING.md with examples of linking to API docs

---

en/components/grid_paging.md
en/components/grid_sorting.md
jp/components/grid_paging.md
jp/components/grid_sorting.md

update paging and sorting topics

---

en/components/list.md
jp/components/list.md

Left and right panning template for IgxList
IgniteUI/igniteui-angular#728

Topic IgxList panning templates

---

en/components/calendar.md
en/components/carousel.md
en/components/circular_progress.md
en/components/date_picker.md
en/components/dialog.md
en/components/grid_displayDensity.md
en/components/grid_multi_column_headers.md
en/components/layout.md
en/components/linear_progress.md
en/components/slider.md
en/components/toggle.md
jp/components/calendar.md
jp/components/carousel.md
jp/components/circular_progress.md
jp/components/date_picker.md
jp/components/dialog.md
jp/components/grid_displayDensity.md
jp/components/grid_multi_column_headers.md
jp/components/layout.md
jp/components/linear_progress.md
jp/components/slider.md
jp/components/toggle.md

Providing Typedoc references for all the feature/components/components-members in the below listed topics:
Cell component
Column group (Multi column headers)
Column component
Grid summary
Grid crud
Pagination
Sorting
Linear Progress bar
Circular Progress bar
Dialog
Slider
Toggle
Layout Manager
Carousel
Calendar
DatePicker

Providing Typedoc and Sassdoc references for EN and JP topics.

---

en/components/icon.md
jp/components/icon.md

Related to IgniteUI/igniteui-angular#2661

docs(icon): Added SVG icons info #2661

---

en/components/expansion_panel.md
jp/components/expansion_panel.md

Related to https://github.com/IgniteUI/igniteui-angular-samples/pull/665

feat: adding weather sample to docs.

---

en/components/expansion_panel.md
en/components/overlay_main.md
en/components/toggle.md
jp/components/overlay_main.md
jp/components/toggle.md

Somewhat related to https://github.com/IgniteUI/igniteui-angular-samples/pull/674

fix: Fixing docs typos.

---

desktop.ini
en/components/grid_groupby.md

Updated IGroupByRecord interface in GroupBy topic.

---

en/components/grid_groupby.md
jp/components/grid_groupby.md

Changed getGroupRow method in group_by topic.

---

en/components/drop_down.md
jp/components/drop_down.md

Related to IgniteUI/igniteui-angular#2031

docs(drop-down): Added notes for onSelection event args. #2031

---

en/components/shadows.md
jp/components/shadows.md

Adding demo on how to customize the shadowing in the Shadow topic.

---

en/components/display_density.md
en/components/input_group.md
en/components/toc.yml
jp/components/display_density.md
jp/components/input_group.md
jp/components/toc.yml
kr/components/display_density.md
kr/components/toc.yml

Related to IgniteUI/igniteui-angular#2692

docs(*): Added topic for display density #2692

---

en/components/doughnutchart.md
en/components/excel_library.md
en/components/excel_library_using_cells.md
en/components/excel_library_using_tables.md
en/components/excel_library_using_workbooks.md
en/components/excel_library_using_worksheets.md
en/components/excel_library_working_with_charts.md
en/components/excel_library_working_with_grids.md
en/components/excel_library_working_with_sparklines.md
en/components/piechart.md
en/components/toc.yml

topics for excel, pie and doughnut charts

---

package-lock.json
package.json

Updated the template to the latest version - https://github.com/IgniteUI/igniteui-docfx-template/releases/tag/v2.0.1.

Updated igniteui-docfx-template to 2.0.1

---

en/components/excel_library_working_with_sparklines.md

mdd-258905

---

en/components/excel_library_using_workbooks.md

mdd-258902

---

en/components/treegrid.md
jp/components/treegrid.md

Change IgxTreeGrid topics to use new filtering property

---

en/components/piechart.md

mdd-259091

---

en/components/overlay_main.md
en/components/overlay_position.md
en/components/overlay_scroll.md
kr/components/overlay_main.md
kr/components/overlay_position.md
kr/components/overlay_scroll.md

Update Stackblitz Button Label

---

en/components/grid.md
jp/components/grid.md

add link to the keyboard nav specification in grid topic

add link to the keyboard nav specification in grid topic

---

en/components/grid_displayDensity.md

Fix typo in Grid Display Density topic.

---

en/components/grid_groupby.md

KB navigation section update in Grid "Group By" topic.

---

en/components/circular_progress.md
en/components/linear_progress.md

Update for Circular and Linear progress bars topics.

---

en/components/excel_library_using_cells.md

mdd-258900

---

en/components/toc.yml

mdd-toc-excel-update

---

en/components/button.md
en/components/buttonGroup.md
en/components/icon.md
en/components/input_group.md
en/components/label_input.md
en/components/radio_button.md
en/components/tabbar.md
jp/components/button.md
jp/components/buttonGroup.md
jp/components/icon.md
jp/components/input_group.md
jp/components/label_input.md
jp/components/radio_button.md
jp/components/tabbar.md
kr/components/button.md
kr/components/buttonGroup.md
kr/components/icon.md
kr/components/input_group.md
kr/components/label_input.md
kr/components/radio_button.md
kr/components/tabbar.md

docs(*): Headers size fixed to be consistent in topics #

---

en/components/excel_library.md
en/components/excel_library_using_cells.md
en/components/excel_library_using_tables.md
en/components/excel_library_using_workbooks.md
en/components/excel_library_using_worksheets.md
en/components/excel_library_working_with_charts.md
en/components/excel_library_working_with_grids.md
en/components/excel_library_working_with_sparklines.md

Bugs Fixed:
259401
259402
259407
259451
259456

Angular Excel doc bug fixing.

---

en/components/excel_library_using_cells.md
en/components/excel_library_using_workbooks.md
en/components/excel_library_working_with_sparklines.md

For TFS items:
259405,
259408,
259457
- Regarding the cell operations topic - there is a lot changed or removed here. Many of the things removed are either not implemented in the Angular tool set or they are not really "cell operations." For example, adding/removing columns and rows is part of the Worksheet Operations topic.

Check-in for Excel doc bugs.

---

en/components/grid_displayDensity.md
en/components/themes/theming-demo.md
en/components/toggle.md
jp/components/grid_displayDensity.md
jp/components/themes/theming-demo.md
jp/components/toggle.md
kr/components/grid_displayDensity.md
kr/components/themes/theming-demo.md
kr/components/toggle.md

Closes #843 
This applies for EN/JP/KR versions.

Fixing and adding links for Display Density/Toggle/Theming Demo topics.

---

en/docfx.json
gulpfile.js
jp/docfx.json
kr/docfx.json
package-lock.json
package.json

Will add issue after we release a new version. This PR is for testing purposes.

Updating template with bundling and minification functionality

---

en/components/drop_down.md
jp/components/drop_down.md
kr/components/drop_down.md

closes #860 
Adding input-dropdown sample. Update Demo sample.

feat: Adding input-dropdown sample. 

---

en/components/list.md
jp/components/list.md
kr/components/list.md

#IgniteUI/igniteui-angular-samples/issues/763

Fixing sample height so it is not cutoff.

---

en/components/navbar.md
jp/components/navbar.md
kr/components/navbar.md

IgniteUI/igniteui-angular#2887
Adding igxActionIcon to Navbar docs.

Adding igxActionIcon to Navbar docs

---

package-lock.json
package.json

Updated igniteui docfx template to 2.0.5

---

en/components/treegrid.md
jp/components/treegrid.md
kr/components/treegrid.md

Added a couple bullets in "Persistence and Integration" section describing how the tree grid gets exported to Excel and CSV.

feat(TreeGridExport): #2982 Adding bullets for exporting.

---

en/components/grid_toolbar.md
jp/components/grid_toolbar.md
kr/components/grid_toolbar.md

IgniteUI/igniteui-angular#2983
Adding docs for the toolbar's custom content outlet feature.

IgxGridToolbar - custom content outlet docs

---

en/components/treegrid.md
en/components/treegrid_batch_editing.md

Add igxTreeGrid batch editing topic.
Closes #889

Add igxTreeGrid batch editing topic, #889

---

en/components/mask.md
jp/components/mask.md
kr/components/mask.md

Related IgniteUI/igniteui-angular#3325

igxMask: add documentation for pipes and placeholder new features

---

en/components/treegrid.md
jp/components/treegrid.md
kr/components/treegrid.md

Reducing a white space and making the first sample taller

---

jp/components/toc.yml
kr/components/toc.yml

Fix toc.yml files

---

en/components/list.md
kr/components/list.md

Changing "Summary" to "References"

---

en/components/grid_editing.md
en/components/ripple.md
jp/components/grid_editing.md
jp/components/ripple.md

Fixing Grid Editing topic minor section and moving IgxRipple polyfill explanation on higher level in topic

---

en/components/banner.md
en/components/snackbar.md
en/components/toast.md
jp/components/banner.md
jp/components/snackbar.md
jp/components/toast.md
kr/components/banner.md
kr/components/snackbar.md
kr/components/toast.md
package-lock.json
package.json

For the following components:
- Banner
- Snackbar
- Toast
please test whether the samples in the corresponding topics open and whether the same samples work in StackBlitz.

Updated notifications samples with the new URLs

---

en/components/dialog.md
en/components/drag_drop.md
en/components/overlay_main.md
en/components/overlay_position.md
en/components/overlay_scroll.md
en/components/ripple.md
en/components/slider.md
en/components/toggle.md
en/components/tooltip.md
jp/components/dialog.md
jp/components/drag_drop.md
jp/components/overlay_main.md
jp/components/overlay_position.md
jp/components/overlay_scroll.md
jp/components/ripple.md
jp/components/slider.md
jp/components/toggle.md
jp/components/tooltip.md
kr/components/dialog.md
kr/components/drag_drop.md
kr/components/overlay_main.md
kr/components/overlay_position.md
kr/components/overlay_scroll.md
kr/components/ripple.md
kr/components/slider.md
kr/components/toggle.md
kr/components/tooltip.md

Please test whether the samples in the corresponding topics open and whether the same samples work in StackBlitz. Components:
- Dialog Window
- Slider
- Ripple
- Toggle
- Tooltip
- Overlay
- Drag and Drop
- Card Sample 1

Interactions bundle

---

package-lock.json
package.json

Update docfx-template version

---

en/components/bulletgraph.md
en/components/lineargauge.md
en/components/radialgauge.md
jp/components/bulletgraph.md
jp/components/lineargauge.md
jp/components/radialgauge.md
kr/components/bulletgraph.md
kr/components/lineargauge.md
kr/components/radialgauge.md

Please test whether the samples in the corresponding topics open and whether the same samples work in StackBlitz. Components:
- Bullet Graph
- Linear Gauge
- Radial Gauge

Gauges bundle

---

en/components/combo.md
en/components/combo_cascading.md
en/components/combo_features.md
en/components/combo_remote.md
en/components/combo_templates.md
en/components/list.md
jp/components/combo.md
jp/components/combo_cascading.md
jp/components/combo_features.md
jp/components/combo_remote.md
jp/components/combo_templates.md
jp/components/list.md
kr/components/combo.md
kr/components/combo_cascading.md
kr/components/combo_features.md
kr/components/combo_remote.md
kr/components/combo_templates.md
kr/components/list.md

Related to #921
For the following components:
- List
- Combo

correct the url to menus samples due to the new lists bundle

---

en/components/excel_library.md
en/components/excel_library_using_cells.md
en/components/excel_library_using_workbooks.md
en/components/excel_library_using_worksheets.md
en/components/excel_library_working_with_charts.md
en/components/excel_library_working_with_grids.md
en/components/excel_library_working_with_sparklines.md
jp/components/excel_library.md
jp/components/excel_library_using_cells.md
jp/components/excel_library_using_workbooks.md
jp/components/excel_library_using_worksheets.md
jp/components/excel_library_working_with_charts.md
jp/components/excel_library_working_with_sparklines.md
kr/components/excel_library.md
kr/components/excel_library_using_cells.md
kr/components/excel_library_using_workbooks.md
kr/components/excel_library_using_worksheets.md
kr/components/excel_library_working_with_charts.md
kr/components/excel_library_working_with_grids.md
kr/components/excel_library_working_with_sparklines.md

Please test whether the excel library samples work.

Excel samples URLs update

---

en/components/display_density.md
en/components/shadows.md
en/components/themes/examples.md
jp/components/display_density.md
jp/components/shadows.md
jp/components/themes/examples.md
kr/components/display_density.md
kr/components/shadows.md
kr/components/themes/examples.md

Please test whether the samples in the corresponding topics open and whether the same samples work in StackBlitz. Components:
- Themes
- Shadows
- Density

Themes bundling

---

en/components/avatar.md
en/components/card.md
en/components/carousel.md
en/components/expansion_panel.md
en/components/layout.md
en/components/tabbar.md
en/components/tabs.md
jp/components/avatar.md
jp/components/card.md
jp/components/carousel.md
jp/components/expansion_panel.md
jp/components/layout.md
jp/components/tabbar.md
jp/components/tabs.md
kr/components/avatar.md
kr/components/card.md
kr/components/carousel.md
kr/components/expansion_panel.md
kr/components/layout.md
kr/components/tabbar.md
kr/components/tabs.md

Please test whether the samples in the corresponding topics open and whether the same samples work in StackBlitz. Components:
- Layout Manager
- Carousel
- Bottom Manager
- Tabs
- Card
- Avatar
- Expansion Panel

correcting layouts samples urls

---

en/components/exporter_csv.md
en/components/exporter_excel.md
en/components/localization.md
jp/components/exporter_csv.md
jp/components/exporter_excel.md
jp/components/localization.md
kr/components/exporter_csv.md
kr/components/exporter_excel.md
kr/components/localization.md

#921 
Sampels to be verified:
CSV Export
Excel Export
Localization

add ursl for services bundle

---

en/components/grid.md
jp/components/grid.md
kr/components/grid.md

Documenting the igx-grid data structure availability.

---

en/components/toc.yml
jp/components/toc.yml
kr/components/toc.yml

Update "New" flags on items

---

en/components/snackbar.md
jp/components/snackbar.md
kr/components/snackbar.md

Closes #925
Adding new section in the snackbar topic related to the custom content functionality.

Add new section to IgxSnackbar topic

---

en/components/grid.md

Documenting styles configuration for IE11 and autoprefixer need

---

en/components/overlay_position.md

The table with defaults was broken. Should be ok now.

Fix defaults for elastic positioning strategy

---

en/global.json
jp/global.json
kr/global.json
package-lock.json
package.json

Adding link to the repos of all the versions in global json file

---

en/components/calendar.md
en/components/expansion_panel.md
jp/components/calendar.md
jp/components/expansion_panel.md
kr/components/calendar.md
kr/components/expansion_panel.md

#966 Fixed broken links to typedocs.

---

en/components/circular_progress.md

Provide documentation for indeterminate circular progress

---

en/components/grid.md
jp/components/grid.md
kr/components/grid.md

restore the initial finjs demo url

---

en/components/combo_features.md
jp/components/combo_features.md
kr/components/combo_features.md

Fix snippet in combo binding example

---

web.config

Adding fonts in webconfig

---

package-lock.json
package.json

Updated DocFX template to 2.0.9

---

package-lock.json
package.json

Updated to the latest version.

Updated igniteui-docfx-template to 2.0.11

---

en/components/combo_templates.md
jp/components/combo_templates.md
kr/components/combo_templates.md

Added proper selectors to code snippets in combo templating section
Added point about templating the combo input group using `igx-prefix` and `label`

Combo - Update Combo templating section with proper selectors

---

en/components/select.md
en/components/toc.yml
jp/components/select.md
jp/components/toc.yml
kr/components/select.md
kr/components/toc.yml

New samples:
- Basic select sample.
- Select with groups sample.
- Select in a form sample.
- Select with custom overlay settings sample.

Add IgxSelect topic

---

en/components/drop_down.md
jp/components/drop_down.md
kr/components/drop_down.md

Added a section on grouping hierarchical data in the drop-down topic.

docs(drop-down): add drop-drop-item-group explanation and code snippets

---

.github/CONTRIBUTING.md

Adding lazy loading section

---

en/.gitignore
gulpfile.js
jp/.gitignore
kr/.gitignore

Ignore only generated files in .gitignore

---

en/components/shadows.md
jp/components/shadows.md
kr/components/shadows.md

Change docs for elevations

---

en/components/texthighlight.md
en/components/toc.yml
jp/components/texthighlight.md
jp/components/toc.yml
kr/components/texthighlight.md
kr/components/toc.yml

Closes IgniteUI/igniteui-angular-samples#1007

Update TextHighlight topic after sample changes

---

en/components/grids_templates/editing.md

#1060 Removed a common update link.

---

en/components/grids_templates/editing.md

#1059 Fixed a parameter in a code snippet.

---

en/components/autocomplete.md
jp/components/autocomplete.md
kr/components/autocomplete.md

Fixing wrong links to the API for the Autocomplete topic

---

en/components/overlay_main.md
en/components/overlay_position.md
en/components/overlay_scroll.md
jp/components/overlay_main.md
jp/components/overlay_position.md
jp/components/overlay_scroll.md

Update of the overlay docs after attach method was added.

Add attach method to overlay docs

---

en/components/general/cli-overview.md
en/components/general/update_guide.md

Adding Ignite UI for React to the explanation of the `ig new` command
+
Fixed typo

Adding Ignite UI for React to the explanation of the ig new command

---

en/components/date_picker.md
en/components/month_picker.md
en/components/toc.yml
jp/components/month_picker.md
jp/components/toc.yml
kr/components/month_picker.md
kr/components/toc.yml

Related to IgniteUI/igniteui-angular#3947

docs(month-picker): Topic for month picker #3947

---

en/components/grids_templates/paging.md

Closes #1082
Fixing code snippet indentations.

Fixing code snippet indentations

---

en/components/drop_down.md
jp/components/drop_down.md
kr/components/drop_down.md

docs(dropdown): update code snippets to match updated samples

---

en/components/overlay_position.md
en/components/overlay_scroll.md
jp/components/overlay_position.md
jp/components/overlay_scroll.md
kr/components/overlay_position.md
kr/components/overlay_scroll.md

Fix overlay topics issues

---

en/components/date_picker.md
en/components/time_picker.md
jp/components/time_picker.md
kr/components/time_picker.md

Related to IgniteUI/igniteui-angular#4143

fix(pickers): Fixed mode references #4143

---

en/components/grids_templates/excel_style_filtering.md
jp/components/grids_templates/excel_style_filtering.md
kr/components/grids_templates/excel_style_filtering.md

Increase ESF sample height

---

en/components/input_group.md
en/components/label_input.md
en/components/mask.md
jp/components/input_group.md
jp/components/label_input.md
jp/components/mask.md
kr/components/input_group.md
kr/components/label_input.md
kr/components/mask.md

docs(): Removed missing links in API #1016

---

en/components/input_group.md
en/components/input_group_reactive_forms.md
jp/components/input_group.md
jp/components/input_group_reactive_forms.md
kr/components/input_group.md
kr/components/input_group_reactive_forms.md

Update code snippets according to the sample in:
- Input Group
- Reactive Forms

Update code snippets according to the sample

---

en/components/button.md
jp/components/button.md
kr/components/button.md

Button samples loading fix

---

en/components/card.md
en/components/grids_templates/column_hiding.md
en/components/list.md
en/components/navbar.md
en/components/snackbar.md
en/components/texthighlight.md
en/components/toast.md
en/components/tooltip.md
jp/components/card.md
jp/components/grids_templates/column_hiding.md
jp/components/list.md
jp/components/navbar.md
jp/components/snackbar.md
jp/components/texthighlight.md
jp/components/toast.md
jp/components/tooltip.md
kr/components/card.md
kr/components/grids_templates/column_hiding.md
kr/components/list.md
kr/components/navbar.md
kr/components/snackbar.md
kr/components/toast.md
kr/components/tooltip.md
kr/components/treegrid/tree_grid.md

Remove controls module links

---

en/components/overlay_main.md
en/components/toggle.md
jp/components/overlay_main.md
jp/components/toggle.md
kr/components/overlay_main.md
kr/components/toggle.md

Fix some links and content in `IgxOverlay` and `IgxToggle` docs.

Overlay and Toggle docs fixes

---

en/components/toggle.md

Add note about how using close on outside click will not work with toggle method

Add notes about close on outside click + toggle

---

en/components/doughnutchart.md
en/components/list.md
en/components/piechart.md
jp/components/doughnutchart.md
jp/components/list.md
jp/components/piechart.md
kr/components/doughnutchart.md
kr/components/list.md
kr/components/piechart.md

Add lazyload in Pie chart Doughnut chart and List topics for all versions

---

en/components/excel_library.md
en/components/excel_library_using_cells.md
en/components/excel_library_using_tables.md
en/components/excel_library_using_workbooks.md
en/components/excel_library_using_worksheets.md
en/components/excel_library_working_with_charts.md
en/components/excel_library_working_with_grids.md
en/components/excel_library_working_with_sparklines.md
jp/components/excel_library.md
jp/components/excel_library_using_cells.md
jp/components/excel_library_using_tables.md
jp/components/excel_library_using_workbooks.md
jp/components/excel_library_using_worksheets.md
jp/components/excel_library_working_with_charts.md
jp/components/excel_library_working_with_grids.md
jp/components/excel_library_working_with_sparklines.md
kr/components/excel_library.md
kr/components/excel_library_using_cells.md
kr/components/excel_library_using_tables.md
kr/components/excel_library_using_workbooks.md
kr/components/excel_library_using_worksheets.md
kr/components/excel_library_working_with_charts.md
kr/components/excel_library_working_with_grids.md
kr/components/excel_library_working_with_sparklines.md

Add lazyload excel_library topics for all versions

---

en/components/calendar.md
en/components/date_picker.md
en/components/exporter_csv.md
en/components/month_picker.md
en/components/time_picker.md
jp/components/calendar.md
jp/components/date_picker.md
jp/components/exporter_csv.md
jp/components/month_picker.md
jp/components/time_picker.md
kr/components/calendar.md
kr/components/date_picker.md
kr/components/exporter_csv.md
kr/components/month_picker.md
kr/components/time_picker.md

Add lazyload in Scheduling and Services topics for all versions

---

en/components/bulletgraph.md
en/components/lineargauge.md
en/components/radialgauge.md
jp/components/bulletgraph.md
jp/components/lineargauge.md
jp/components/radialgauge.md
kr/components/bulletgraph.md
kr/components/lineargauge.md
kr/components/radialgauge.md

Add lazyload  in Gauges topics for all versions

---

en/components/banner.md
en/components/navbar.md
en/components/navdrawer.md
en/components/snackbar.md
en/components/toast.md
jp/components/banner.md
jp/components/navbar.md
jp/components/navdrawer.md
jp/components/snackbar.md
jp/components/toast.md
kr/components/banner.md
kr/components/navbar.md
kr/components/navdrawer.md
kr/components/snackbar.md
kr/components/toast.md

Add lazyload in Menus and Notification topics for all versions

---

en/components/grids_templates/column_hiding.md
en/components/grids_templates/excel_style_filtering.md
en/components/grids_templates/filtering.md
en/components/grids_templates/paging.md
en/components/grids_templates/summaries.md
en/components/grids_templates/toolbar.md
en/components/grids_templates/virtualization.md
jp/components/grids_templates/column_hiding.md
jp/components/grids_templates/excel_style_filtering.md
jp/components/grids_templates/filtering.md
jp/components/grids_templates/paging.md
jp/components/grids_templates/summaries.md
jp/components/grids_templates/toolbar.md
jp/components/grids_templates/virtualization.md
kr/components/grids_templates/column_hiding.md
kr/components/grids_templates/excel_style_filtering.md
kr/components/grids_templates/filtering.md
kr/components/grids_templates/paging.md
kr/components/grids_templates/summaries.md
kr/components/grids_templates/toolbar.md
kr/components/grids_templates/virtualization.md

Adding lazyloading for Grid Templates

---

en/components/grid/grid.md
en/components/themes/examples.md
en/components/treegrid/tree_grid.md
jp/components/grid/grid.md
jp/components/themes/examples.md
jp/components/treegrid/tree_grid.md
kr/components/grid/grid.md
kr/components/themes/examples.md
kr/components/treegrid/tree_grid.md

Adding lazyload for IgxGrid and TreeGrid topics all versions

---

en/components/categorychart.md
en/components/categorychart_annotation_layers.md
en/components/categorychart_axis_options.md
en/components/categorychart_configuration_options.md
en/components/categorychart_high_volume_data.md
en/components/categorychart_highlighting.md
en/components/categorychart_real_time_data.md
en/components/categorychart_tooltip_templates.md
en/components/categorychart_tooltip_types.md
jp/components/categorychart.md
jp/components/categorychart_annotation_layers.md
jp/components/categorychart_axis_options.md
jp/components/categorychart_configuration_options.md
jp/components/categorychart_custom_tooltips.md
jp/components/categorychart_explore_chart_types.md
jp/components/categorychart_high_volume_data.md
jp/components/categorychart_highlighting.md
jp/components/categorychart_real_time_data.md
jp/components/categorychart_tooltip_templates.md
jp/components/categorychart_tooltip_types.md
kr/components/categorychart.md
kr/components/categorychart_annotation_layers.md
kr/components/categorychart_axis_options.md
kr/components/categorychart_configuration_options.md
kr/components/categorychart_explore_chart_types.md
kr/components/categorychart_high_volume_data.md
kr/components/categorychart_highlighting.md
kr/components/categorychart_real_time_data.md
kr/components/categorychart_tooltip_templates.md
kr/components/categorychart_tooltip_types.md

Add loading classes for category chart topics all versions

---

en/components/select.md
jp/components/select.md
kr/components/select.md

Related to https://github.com/IgniteUI/igniteui-angular/pull/4177

Remove closeOnOutsideClick and modal overlay properties

---

en/components/grids_templates/virtualization.md
jp/components/grids_templates/virtualization.md

IgniteUI/igniteui-angular-samples#1062

Add Tree Grid Remote Filtering docs

---

en/components/dialog.md
jp/components/dialog.md
kr/components/dialog.md

docs(dialog): Added info about retemplating title/actions

---

en/components/grids_templates/filtering.md
jp/components/grids_templates/filtering.md
kr/components/grids_templates/filtering.md

Add sample for igxFilterCellTemplate

---

en/components/buttonGroup.md
jp/components/buttonGroup.md
kr/components/buttonGroup.md

docs(button-group): Snippets updated, added more info #1006

---

package-lock.json
package.json

Updating natives package to 1.1.6

---

en/components/grids_templates/selection.md
jp/components/grids_templates/selection.md
kr/components/grids_templates/selection.md

Close #1037 
This PR should be merged once the sample is merged in angular-samples

Mcs topic update

---

en/components/toc.yml
jp/components/toc.yml
kr/components/toc.yml

@nrobakova could you please verify that everything is rendered fine with the Table of contant, and red label "new" is present.

Adding new label to Selection topic

---

en/components/date_picker.md
en/components/toc.yml
jp/components/date_picker.md
jp/components/toc.yml
kr/components/date_picker.md
kr/components/toc.yml

* Removed tag NEW from DataGrid Conditional Cell Styling sample
* date picker drop down sample container enlarged

fix(*): Fixed minor issues #

---

en/components/date_picker.md
jp/components/date_picker.md
kr/components/date_picker.md

Related to IgniteUI/igniteui-angular#4229 and IgniteUI/igniteui-angular-samples#1095

docs(date-picker): Added info for drop-down mode re-templating

---

en/components/grids_templates/column_moving.md
jp/components/grids_templates/column_moving.md
kr/components/grids_templates/column_moving.md

Closes IgniteUI/igniteui-angular-samples#1105

Add a not related to fixing pinning in grid column moving

---

en/components/drop_down_virtual.md
en/components/toc.yml
jp/components/drop_down_virtual.md
jp/components/toc.yml
kr/components/drop_down_virtual.md
kr/components/toc.yml
package-lock.json

Related https://github.com/IgniteUI/igniteui-angular-samples/pull/1102

docs(drop-down): add virtual drop-down topic

---

en/components/hierarchicalgrid/hierarchical_grid.md

Making the image responsive in the igxHierarchicalGrid Overview topic

---

jp/components/chip.md

Remove whitespace on iframe id

---

en/components/button.md
jp/components/button.md
kr/components/button.md

IgniteUI/igniteui-angular#4502

[DO NOT MERGE] Update button topic with display density

---

en/components/list.md
jp/components/list.md
kr/components/list.md

IgniteUI/igniteui-angular#4393

[DO NOT MERGE] Update list topic with display density

---

en/global.json
jp/global.json
kr/global.json

Adding global varibale for theme enabling/disabling

---

en/components/grids_templates/editing.md
en/components/grids_templates/row_editing.md
jp/components/grids_templates/editing.md
jp/components/grids_templates/row_editing.md
kr/components/grids_templates/editing.md
kr/components/grids_templates/row_editing.md

Related to bug #[4313](https://github.com/IgniteUI/igniteui-angular/issues/4313)

Update documentation about exiting edit mode 

---

en/.gitignore
en/components/toc.yml
en/components/treegrid/load_on_demand.md
gulpfile.js
jp/.gitignore
jp/components/toc.yml
jp/components/treegrid/load_on_demand.md
kr/.gitignore
kr/components/toc.yml
kr/components/treegrid/load_on_demand.md

IgniteUI/igniteui-angular#4257

Add Tree Grid Load on Demand topic

---

en/components/grid/grid.md
jp/components/grid/grid.md
kr/components/grid/grid.md

Add state persistence topic

---

en/components/grids_templates/selection.md
kr/components/grids_templates/selection.md

Fixing typo in selection grid template

---

en/components/grids_templates/row_drag.md

Change which sample is used in the row-draggable topics
***DEPENDS ON*** https://github.com/IgniteUI/igniteui-angular-samples/pull/1157

chore(row-drag): change base row drag sample

---

en/components/chip.md
jp/components/chip.md
jp/components/dialog.md
jp/components/hierarchicalgrid/load_on_demand.md
jp/components/month_picker.md
jp/components/themes/examples.md
jp/components/treegrid/tree_grid.md
jp/components/treegrid/treegrid_batch_editing.md
kr/components/banner.md
kr/components/chip.md
kr/components/display_density.md
kr/components/divider.md
kr/components/drop_down_virtual.md
kr/components/general/cli-overview.md
kr/components/general/getting_started.md
kr/components/general/update_guide.md
kr/components/grids_templates/excel_style_filtering.md
kr/components/hierarchicalgrid/hierarchical_grid.md
kr/components/hierarchicalgrid/load_on_demand.md
kr/components/localization.md
kr/components/month_picker.md
kr/components/select.md
kr/components/treegrid/load_on_demand.md
kr/components/treegrid/tree_grid.md
kr/components/treegrid/treegrid_batch_editing.md
package-lock.json
package.json

Fixed broken links

---

en/components/buttonGroup.md
jp/components/buttonGroup.md
kr/components/buttonGroup.md

IgniteUI/igniteui-angular#4532

Update IgxButtonGroup topic with display density

---

gulpfile.js
package-lock.json
package.json

Downgrading gulp and browsersync

---

en/components/button.md
en/components/buttonGroup.md
en/components/expansion_panel.md
en/components/grids_templates/row_drag.md
en/components/grids_templates/selection.md
en/components/overlay_main.md
en/docfx.json
jp/components/button.md
jp/components/buttonGroup.md
jp/components/expansion_panel.md
jp/components/grids_templates/multi_row_layout.md
jp/components/grids_templates/row_drag.md
jp/components/grids_templates/selection.md
jp/components/overlay_main.md
jp/components/treegrid/treegrid_batch_editing.md
jp/components/treegrid/treegrid_row_editing.md
jp/docfx.json
kr/components/button.md
kr/components/buttonGroup.md
kr/components/expansion_panel.md
kr/components/grids_templates/selection.md
kr/components/overlay_main.md
kr/components/treegrid/treegrid_batch_editing.md
kr/components/treegrid/treegrid_row_editing.md
kr/docfx.json

Reduce build warnings

---

en/components/button.md
en/components/buttonGroup.md
en/components/expansion_panel.md
en/components/grids_templates/row_drag.md
en/components/grids_templates/selection.md
en/components/overlay_main.md
en/docfx.json
jp/components/button.md
jp/components/buttonGroup.md
jp/components/expansion_panel.md
jp/components/grids_templates/multi_row_layout.md
jp/components/grids_templates/row_drag.md
jp/components/grids_templates/selection.md
jp/components/overlay_main.md
jp/components/treegrid/treegrid_batch_editing.md
jp/components/treegrid/treegrid_row_editing.md
jp/docfx.json
kr/components/button.md
kr/components/buttonGroup.md
kr/components/expansion_panel.md
kr/components/grids_templates/selection.md
kr/components/overlay_main.md
kr/components/treegrid/treegrid_batch_editing.md
kr/components/treegrid/treegrid_row_editing.md
kr/docfx.json

Reduce build warnings MASTER

---

en/components/slider.md
jp/components/slider.md
kr/components/slider.md

Extending slider topic with the new labels feature 7.3.x

---

en/components/grids_templates/paging.md
jp/components/grids_templates/paging.md

IgniteUI/igniteui-angular-samples#1181

Add docs for tree grid remote paging

---

package-lock.json
package.json

Update docfx-templat to 2.0.21

---

en/components/date_picker.md
en/components/time_picker.md
jp/components/date_picker.md
jp/components/time_picker.md
kr/components/date_picker.md
kr/components/time_picker.md

Related samples update https://github.com/IgniteUI/igniteui-angular-samples/pull/1197

docs(date, time pickers): Updating drop down info

---

en/components/grids_templates/selection.md

Closes #1265 
This PR should be tested after this PR is merged in igniteui-angular-samples:
- [https://github.com/IgniteUI/igniteui-angular-samples/pull/1178](https://github.com/IgniteUI/igniteui-angular-samples/pull/1178)

Adding context menu section for IgxGrid selection topic

---

en/components/grids_templates/selection.md

Change code snippet for context menu section(7.3.x)

---

en/components/general/update_guide.md
jp/components/general/update_guide.md
kr/components/general/update_guide.md

Adding section for updating from 7.1.x to 8.0.x

---

en/components/grids_templates/selection.md

Change code snippet for context menu section(master)

---

.github/CONTRIBUTING.md
en/index.md
jp/index.md
kr/index.md

Replace index.html  with getting started.html

---

en/components/grids_templates/column_resizing.md
jp/components/grids_templates/column_resizing.md

docs(grid): Added styling section in the resizing topics for grids

---

en/components/grids_templates/column_moving.md
jp/components/grids_templates/column_moving.md

Related to #1275 use branch https://github.com/IgniteUI/igniteui-angular-samples/pull/1213

docs(grid): add topic for grids themed

---

en/components/icon.md
jp/components/icon.md

Related to IgniteUI/igniteui-angular#5218

docs(icon): Added a note for universal app exception 

---

en/components/grids_templates/paging.md
jp/components/grids_templates/paging.md

Adding iframe for grid paging styling section

---

en/components/toc.yml
jp/components/toc.yml
kr/components/toc.yml

- added nodes for new GeoMap topics
- moved nodes for existing GeoMap above Frameworks
- moved nodes for existing FinChart topics in alphabetical order
- ported localized strings

ported GeoMap changes from xplatform TOC

---

en/components/grids_templates/multi_column_headers.md
jp/components/grids_templates/multi_column_headers.md

IgniteUI/igniteui-angular#3344

Add multi column header template docs

---

en/components/grids_templates/paging.md
jp/components/grids_templates/paging.md

Changing code snippets based on the new paginator

---

en/components/grids_templates/multi_column_headers.md
jp/components/grids_templates/multi_column_headers.md

IgniteUI/igniteui-angular#3344

Add column group template docs

---

en/components/grids_templates/column_hiding.md
jp/components/grids_templates/column_hiding.md

Add styling section to column hiding topic

---

en/components/grids_templates/toolbar.md
jp/components/grids_templates/toolbar.md

Add styling sections to toolbar topic

---

en/components/tooltip.md
jp/components/tooltip.md

Add styling section to tooltip topic

---

en/components/tabbar.md
en/components/tabs.md

IgniteUI/igniteui-angular#4297

Adding Tabs/BottomNav Routing Docs

---

en/components/combo.md
en/components/drop_down.md
en/components/select.md
jp/components/combo.md
jp/components/drop_down.md
jp/components/select.md

Update styles sections - palette and colors for igxDropDown based components.

---

jp/components/tabbar.md
jp/components/tabs.md

IgniteUI/igniteui-angular#4297

Adding routing for tabs/bottomNav in JP files

---

en/index.md
jp/index.md
kr/index.md

Removing "includes" check in index file for IE compatibility

---

en/components/checkbox.md
jp/components/checkbox.md

Related https://github.com/IgniteUI/igniteui-angular-samples/pull/1307

Add checkbox styling section

---

en/components/toc.yml
jp/components/toc.yml
kr/components/toc.yml

Updated new tags for treegrid, hierarchical grid & ESF. #1391

---

en/components/grids_templates/selection.md

Fix button data-iframe-id

---

en/components/button.md
jp/components/button.md

Add styling section to button topic

---

en/components/piechart.md
en/components/zoomslider_overview.md

Fix iframes src values

---

en/components/general/cli-overview.md
en/components/grids_templates/batch_editing.md
en/components/grids_templates/editing.md
en/components/overlay_styling.md
en/components/transaction-classes.md
en/components/transaction.md
jp/components/grids_templates/editing.md
jp/components/overlay_styling.md
jp/components/transaction-classes.md
jp/components/transaction.md

fix(transaction,cli,grids): broken links, grid editing typos

---

en/components/grids_templates/row_editing.md
jp/components/grids_templates/row_editing.md

fix: Update topics to reflect latest samples.
Closes #1413 
Related: https://github.com/IgniteUI/igniteui-angular-samples/pull/1322/

Update topics to reflect latest samples

---

en/components/buttonGroup.md
jp/components/buttonGroup.md

Add button group styling section

---

en/components/grids_templates/excel_style_filtering.md
jp/components/grids_templates/excel_style_filtering.md

Fix stackblitz demo link in Excel Style Filtering topic

---

en/components/combo.md
en/components/input_group.md
en/components/select.md
jp/components/combo.md
jp/components/input_group.md
jp/components/select.md

Add checkbox link and update sample height

---

en/components/button.md
en/components/tooltip.md
jp/components/button.md
jp/components/tooltip.md

Fix links in tooltip and button topics

---

en/components/general/wpf_to_angular_guide/angular_events.md
en/components/general/wpf_to_angular_guide/angular_pipes.md
en/components/general/wpf_to_angular_guide/create_first_angular_app.md
en/components/general/wpf_to_angular_guide/create_ui_with_components.md
en/components/general/wpf_to_angular_guide/one_way_binding.md
en/components/general/wpf_to_angular_guide/structural_directives.md
en/components/general/wpf_to_angular_guide/two_way_binding.md

Made some small changes to the WPF to Angular guidance topics.
- embedded the related videos at the top of each topic.
- made small text edits to improve readability and flow.

Wpf to Angular edits

---

en/components/dialog.md
jp/components/dialog.md

Add dialog styling documentation

---

en/components/grids_templates/filtering.md
jp/components/grids_templates/filtering.md

Add styling section to grid/treegrid/hierarchicalgrid filtering topic

---

en/components/calendar.md
jp/components/calendar.md

Add calendar styling documentation

---

en/components/card.md
jp/components/card.md

https://github.com/IgniteUI/igniteui-docfx/issues/1275

docs(cards): Adding styling section to cards topic

---

en/components/grids_templates/excel_style_filtering.md
en/components/grids_templates/filtering.md
jp/components/grids_templates/excel_style_filtering.md
jp/components/grids_templates/filtering.md

Adding styling section to ESF topics for all grids

---

en/components/drag_drop.md
jp/components/drag_drop.md
kr/components/drag_drop.md

chore(*): Changing D&D puzzle sample with icons sample

---

en/components/grids_templates/selection.md
jp/components/grids_templates/selection.md
kr/components/grids_templates/selection.md

Closes [igniteui-angular-samples Issue #1170](https://github.com/IgniteUI/igniteui-angular-samples/issues/1170)

Adds Sample for Selection-based Summaries

---

en/components/combo.md
en/components/for_of.md
en/components/grid/grid.md
en/components/hierarchicalgrid/hierarchical_grid.md
en/components/treegrid/tree_grid.md
jp/components/combo.md
jp/components/for_of.md
jp/components/grid/grid.md
jp/components/hierarchicalgrid/hierarchical_grid.md
jp/components/treegrid/tree_grid.md
kr/components/combo.md
kr/components/for_of.md
kr/components/grid/grid.md
kr/components/hierarchicalgrid/hierarchical_grid.md
kr/components/treegrid/tree_grid.md

Closes #1270
For reference: IgniteUI/igniteui-angular#4884

Document igxForOf/igxGrid etc. known issue when working with hidden containers like igxTabs

---

en/components/select.md

Add How to use required section 

---

en/components/select.md
jp/components/select.md

Related https://github.com/IgniteUI/igniteui-docfx/pull/1421

Add declarative item and label.

---

en/components/navbar.md
jp/components/navbar.md

Add navbar style docs

---

en/components/snackbar.md
jp/components/snackbar.md

Add snackbar style docs

---

en/components/grid/groupby.md
jp/components/grid/groupby.md
kr/components/grid/groupby.md

Adds Group By Styling Topic

---

en/global.json
jp/global.json
kr/global.json

Adding Demos base url variable in global.json

---

package-lock.json
package.json

Update docfx-temlate to 2.0.24

---

en/components/chip.md
en/components/grid/groupby.md
en/components/grids_templates/column_pinning.md
en/components/grids_templates/editing.md
jp/components/chip.md
jp/components/grid/groupby.md
jp/components/grids_templates/column_pinning.md
kr/components/chip.md
kr/components/grid/groupby.md
kr/components/grids_templates/column_pinning.md

Copyright of the Styling section is for @3phase 
Related to: https://github.com/IgniteUI/igniteui-docfx/pull/1478

Adds Topic for Chip Styling

---

en/components/grids_templates/excel_style_filtering.md
jp/components/grids_templates/excel_style_filtering.md

Add ESF Load On Demand docs

---

en/components/general/update_guide.md
jp/components/general/update_guide.md
kr/components/general/update_guide.md

Related to changes introduced in [#5630](https://github.com/IgniteUI/igniteui-angular/pull/5630)

Add update guide related to changes in the IgxDrag/IgxDrop directive in 8.2.x.

---

en/components/general/wpf_to_angular_guide/layout.md

docs(general): SEO optimizations for WPFtoAngular #1447

---

en/components/drag_drop.md
en/components/select.md

Adding new functionalities to the Drag and Drop topic

---

en/components/dialog.md
jp/components/dialog.md

Adding position and animation settings

---

package-lock.json
package.json

Updating template to 2.0.25 (vnext)

---

package-lock.json
package.json

Update template to 2.0.25 (master)

---

en/components/chip.md
en/components/grid/groupby.md
en/components/grids_templates/column_pinning.md
en/components/grids_templates/multi_row_layout.md
en/components/hierarchicalgrid/hierarchical_grid.md
en/components/icon.md
en/components/ripple.md
jp/components/chip.md
jp/components/grid/groupby.md
jp/components/grids_templates/column_pinning.md
jp/components/grids_templates/multi_row_layout.md
jp/components/hierarchicalgrid/hierarchical_grid.md
jp/components/icon.md
jp/components/ripple.md
kr/components/chip.md
kr/components/grid/groupby.md
kr/components/grids_templates/column_pinning.md
kr/components/grids_templates/multi_row_layout.md
kr/components/hierarchicalgrid/hierarchical_grid.md
kr/components/icon.md
kr/components/ripple.md

Issue to be closed: IgniteUI/igniteui-angular-samples#1461

Fixes styling topics theme switch behavior

---

en/components/grids_templates/row_selection.md

feat(grid): add row selector templating section

---

en/components/grids_templates/live_data.md
jp/components/grids_templates/live_data.md

Update text based on new Chart representation

---

en/components/card.md
jp/components/card.md

docs(horizontal card sample): Update the sample doc to correspond the new styling of the sample

---

en/components/grids_templates/advanced_filtering.md
en/components/toc.yml
jp/components/grids_templates/advanced_filtering.md
jp/components/toc.yml

Add Advanced Filtering topic

---

en/components/general/update_guide.md
en/components/grids_templates/row_drag.md

closes #1485 
Updating the row drag topics after the recent drag/drop changes
Adding to the Update guide the changes to the event arguments

Updating Grid Row Drag topics + Update guide

---

en/components/overlay_position.md

Refactor position strategies section

---

en/components/calendar.md
en/components/date_picker.md
jp/components/calendar.md
jp/components/date_picker.md
kr/components/calendar.md
kr/components/date_picker.md

add calendar and datepicker multiview sections

---

en/components/tabs.md
jp/components/tabs.md

Add tabs style docs

---

en/components/badge.md
jp/components/badge.md

Added badge styling topic

---

en/components/circular_progress.md
jp/components/circular_progress.md

Add circular progress bar styling section

---

en/components/linear_progress.md
jp/components/linear_progress.md

Add linear progress bar styling section

---

en/components/grids_templates/excel_style_filtering.md
jp/components/grids_templates/excel_style_filtering.md
kr/components/grids_templates/excel_style_filtering.md

IgniteUI/igniteui-angular-samples#1490

Fix Excel Style filtering template directive names

---

en/components/select.md

Closes #1481
Related https://github.com/IgniteUI/igniteui-angular-samples/pull/1501

Update select groups section

---

en/components/grids_templates/export_excel.md
jp/components/grids_templates/export_excel.md

Add export grouping as limitation - vNext

---

en/components/grid/grid.md
jp/components/grid/grid.md

IgniteUI/igniteui-angular#5842

Update persistence sample height - vNext

---

en/components/grids_templates/export_excel.md
jp/components/grids_templates/export_excel.md

Add export grouping as limitation - master

---

en/components/grids_templates/conditional_cell_styling.md
jp/components/grids_templates/conditional_cell_styling.md

Add known limitations section 

---

en/components/grids_templates/conditional_cell_styling.md
jp/components/grids_templates/conditional_cell_styling.md

Add known limitations section

---

en/components/grid/grid.md
jp/components/grid/grid.md

IgniteUI/igniteui-angular#5842

Update persistence sample height - master

---

package-lock.json
package.json

You can test this by comparing the [current Global navigation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html) and footer with the changed one.
Test this with all lang versions:
- npm run start
- npm run start -- --lang=jp
- npm run start -- --lang=kr

Update docfx template to 2.1.0

---

en/components/tabbar.md
jp/components/tabbar.md

Add bottomNav style docs - master

---

en/components/themes/global-theme.md
jp/components/themes/global-theme.md

docs(themes): add fluent theme section in the global theme doc

---

en/components/treegrid/tree_grid.md
jp/components/treegrid/tree_grid.md

Add tree grid style docs - vNext

---

package-lock.json
package.json

Remove carrets from igniteui-docfx-template

---

en/components/general/cli/step-by-step-guide.md
en/components/general/getting_started.md

Update getting started topic - vNext

---

en/components/themes/global-theme.md
jp/components/themes/global-theme.md

docs(Themes): Add a docs section with snippet for switching from Material to Fluent Design theme

---

en/components/texthighlight.md
jp/components/texthighlight.md

Add text-highlight directive style docs - vNext

---

en/components/general/cli/step-by-step-guide.md
en/components/general/getting_started.md

Update getting started topic

---

en/components/select.md

- Closes #1610 
- Only EN select.md file is updated.

Add select-item text description under usage section

---

en/components/select.md

- Closes #1610 
- Only EN select.md file is updated.

Add select-item text description under usage section 

---

package-lock.json
package.json

Update to 2.3.0

---

en/components/general/framework-and-features/ssr-rendering.md
jp/components/general/framework-and-features/ssr-rendering.md
jp/components/toc.yml

SSR topic changes

---

en/components/general/framework-and-features/ssr-rendering.md
en/components/toc.yml
jp/components/general/framework-and-features/ssr-rendering.md
jp/components/toc.yml

Add ssr topic EN and JP

---

package-lock.json
package.json

Update version to 2.3.0

---

package-lock.json
package.json

Related to https://github.com/IgniteUI/igniteui-docfx-template/issues/137

Update to 2.3.1

---

en/components/grids_templates/filtering.md
en/components/grids_templates/sorting.md
en/components/grids_templates/virtualization.md
jp/components/grids_templates/filtering.md
jp/components/grids_templates/sorting.md
jp/components/grids_templates/virtualization.md

Update grid remote sorting/filtering docs - vNext

---

en/components/grids_templates/filtering.md
jp/components/grids_templates/filtering.md

Add detectChanges call to initial filter state section - vNext

---

en/components/grids_templates/filtering.md
jp/components/grids_templates/filtering.md

Add detectChanges call to initial filter state section - master

---

en/components/grids_templates/conditional_cell_styling.md
en/components/toc.yml
jp/components/grids_templates/conditional_cell_styling.md
jp/components/toc.yml

Conditional cell styling topic - master

---

en/components/drag_drop.md
en/components/overlay_position.md
en/components/toggle.md

 Add sections about 'setOffset()' - vNext

---

en/components/grids_templates/column_pinning.md

docs(pinning): removing limitations after pinning was changed in code… - VNEXT

---

en/components/grids_templates/column_pinning.md

docs(pinning): removing limitations after pinning was changed in code… - MASTER

---

en/components/grids_templates/row_drag.md

Adding a section about custom ghost template

---

en/components/general/framework-and-features/data-analysis.md
en/components/toc.yml
jp/components/general/framework-and-features/data-analysis.md
jp/components/toc.yml

Add data analysis topic

---

en/components/general/cli/auth-template.md

Add a snippet for ng schematics in Authentication Project Template topic

Adding a schematics snippet

---

package-lock.json
package.json

Updating docfx-template to 2.4.7

---

en/components/grid/grid.md
en/components/grid/master_detail.md
en/components/grids_templates/column_resizing.md
en/components/grids_templates/live_data.md
en/components/treegrid/aggregations.md
en/components/treegrid/tree_grid.md
jp/components/grid/grid.md
jp/components/grid/master_detail.md
jp/components/grids_templates/column_resizing.md
jp/components/grids_templates/live_data.md
jp/components/treegrid/aggregations.md
jp/components/treegrid/tree_grid.md
kr/components/grid/grid.md
kr/components/grids_templates/column_resizing.md
kr/components/treegrid/aggregations.md
kr/components/treegrid/tree_grid.md

Adding lobDemosBaseUrl environment variable

---

jp/components/toc.yml
jp/toc.yml
kr/components/toc.yml
kr/toc.yml

Adding _language property in toc files

---

en/components/grid/grid.md
en/components/grid/master_detail.md
en/components/grids_templates/column_resizing.md
en/components/grids_templates/live_data.md
en/components/treegrid/aggregations.md
en/components/treegrid/tree_grid.md
jp/components/grid/grid.md
jp/components/grid/master_detail.md
jp/components/grids_templates/column_resizing.md
jp/components/grids_templates/live_data.md
jp/components/treegrid/aggregations.md
jp/components/treegrid/tree_grid.md
kr/components/grid/grid.md
kr/components/grids_templates/column_resizing.md
kr/components/treegrid/aggregations.md
kr/components/treegrid/tree_grid.md

Fix lob samples stackblitz button

---

en/components/grid/master_detail.md
jp/components/grid/master_detail.md

Updating docs with changes introduced in: https://github.com/IgniteUI/igniteui-angular/pull/6525

chore(*): Update docs with API changes.

---

en/components/general/framework-and-features/data-analysis.md
jp/components/general/framework-and-features/data-analysis.md

Fix src in iframe

---

en/global.json
jp/global.json
kr/global.json
kr/toc.yml
package-lock.json
package.json

Reverts IgniteUI/igniteui-docfx#1740

Revert "Replaced kr domains to use infragistics.co.kr"

---

en/components/general/cli-overview.md
jp/components/general/cli-overview.md

The id was changed from "empty-project" to "empty".

Updating empty project template id from "empty-project" to "empty"

---

en/components/badge.md
jp/components/badge.md
kr/components/badge.md

fix(badge): fixing the avatar + badge #1721

---

en/components/grids_templates/row_selection.md
jp/components/grids_templates/row_selection.md

Fixing demos-base-urls attributes (vNext)

---

en/components/toc.yml
jp/components/toc.yml

docs(*): update tags - add/remove new #1785

---

en/components/general/framework-and-features/framework-and-features.md
en/components/toc.yml
jp/components/general/framework-and-features/framework-and-features.md
jp/components/toc.yml

Rtl changes a11y vnext

---

en/components/general/framework-and-features/framework-and-features.md
en/components/toc.yml
jp/components/general/framework-and-features/framework-and-features.md
jp/components/toc.yml

Add rtl support section

---

en/components/layout.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1824

docs(layout manager): update docs for layout manager

---

en/components/avatar.md

Linked issues: IgniteUI/igniteui-angular-samples#1810

Refactor avatar documentation

---

en/components/carousel.md

Linked issues: IgniteUI/igniteui-angular-samples#1805

Edited documentation of the carousel component

---

en/components/themes/component-themes.md
en/components/themes/global-theme.md

IgniteUI/igniteui-angular#6803

docs(themes): update docs for legacy support set to false.

---

en/components/card.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1828

docs(card): update docs for card.

---

en/components/tabbar.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1834

docs(tabbar): update docs for bottom navigation(tabbar)

---

en/components/snackbar.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1856

docs(snackbar) update docs for snackbar

---

en/components/toast.md

Linked issues: https://github.com/IgniteUI/igniteui-angular-samples/issues/1846

docs(toast component): refactor toast component documentation

---

en/components/navbar.md

Linked issues: IgniteUI/igniteui-angular-samples/issues/1843

docs(navbar): navbar documentation refactoring

---

en/components/date_picker.md
en/components/navdrawer.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1862

docs(navdrawer): update documentation for navdrawer

---

en/components/themes/themes-list/bootstrap.md
en/components/themes/themes-list/fluent.md
en/components/themes/themes-list/material.md
jp/components/themes/themes-list/bootstrap.md
jp/components/themes/themes-list/fluent.md
jp/components/themes/themes-list/material.md

fix misspelling igc-core to igx-core

---

en/components/general/angular-grid-overview-guide.md

Responsify Images (vNext)

---

en/components/general/angular-grid-overview-guide.md

Responsify Images (master) #1863

---

web.config

Remove file extensions configs

Web.config update

---

web.config

Update web config mime types master

---

PULL_REQUEST_TEMPLATE.md

chore: add SEO link

---

.github/PULL_REQUEST_TEMPLATE.md

Closes # 
<br />
<br />
<br />

chore: move PR template

---

en/components/grids_templates/column_selection.md
jp/components/grids_templates/column_selection.md

Updating column selection topic with latest changes

---

en/components/toc.yml
package-lock.json
package.json

Closes # 
<br />
<br />
<br />

Update docfx version to 2.6.1

---

en/components/toc.yml
jp/components/toc.yml
package-lock.json
package.json

Closes # 
<br />
<br />
<br />

Update docfx template to 2.6.1

---

en/components/date_picker.md

Linked Issues: IgniteUI/igniteui-angular-samples/issues/1904
<br />
<br />
<br />

docs(date-picker): refactor date-picker documentation

---

en/components/time_picker.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1922

docs(time picker): update time picker documentation

---

en/docfx.json
jp/docfx.json
kr/docfx.json

Enabling cache clear (vnext)

---

en/components/buttonGroup.md

Linked Issues: IgniteUI/igniteui-angular-samples/issues/1925 
<br />
<br />
<br />

docs(button-group): edit button group documentation

---

en/components/button.md

Linked Issues: IgniteUI/igniteui-angular-samples/issues/1924
<br />
<br />
<br />

docs(button): edit button documentation

---

en/components/date_time_editor.md

Small fixes to wording and grammar.

Editorial updates

---

package-lock.json
package.json

Now the TOC filtering should work as expected
<br />
<br />
<br />

Update docfx-template version to 2.6.2

---

package-lock.json
package.json

Closes # 
<br />
<br />
<br />

[master] Update docfx-template version to 2.6.2

---

jp/components/date_picker.md
jp/components/general/framework-and-features/framework-and-features.md
jp/components/grids_templates/virtualization.md
jp/components/toc.yml

Updating localization for master. Fixing issues reported by Marketing.

---

en/components/grids_templates/row_pinning.md

Making minor improvements to the topic

---

en/components/label_input.md

Linked Issues: IgniteUI/igniteui-angular-samples/issues/1951
<br />
<br />
<br />

docs(label&input): improve label & input documentation

---

en/components/grids_templates/keyboard_navigation.md
jp/components/grids_templates/keyboard_navigation.md

Closes #1914
<br />
<br />
<br />

Keyboard navigation topic update

---

en/components/general/framework-and-features/framework-and-features.md
jp/components/general/framework-and-features/framework-and-features.md

Closes #1920
<br />
<br />
<br />

feat(rtl): add section regarding theming engine

---

en/components/grids_templates/keyboard_navigation.md
jp/components/grids_templates/keyboard_navigation.md

Closes # 
<br />
<br />
<br />

Updating base url

---

en/components/toc.yml
jp/components/toc.yml

Closes # 
<br />
<br />
<br />

Update label of kb nav topic

---

en/components/general/wpf_to_angular_guide/angular_events.md
en/components/general/wpf_to_angular_guide/angular_pipes.md
en/components/general/wpf_to_angular_guide/create_first_angular_app.md
en/components/general/wpf_to_angular_guide/create_ui_with_components.md
en/components/general/wpf_to_angular_guide/layout.md
en/components/general/wpf_to_angular_guide/one_way_binding.md
en/components/general/wpf_to_angular_guide/structural_directives.md
en/components/general/wpf_to_angular_guide/two_way_binding.md
en/components/general/wpf_to_angular_guide/wpf_to_angular_guide.md

Closes # 
<br />
<br />
<br />

Improve SEO of WPF to Angular guide

---

en/components/linear_progress.md

https://github.com/IgniteUI/igniteui-angular-samples/pull/1970
<br />
<br />
<br />

docs(linear progress): update linear progress and add more sections

---

en/components/circular_progress.md

https://github.com/IgniteUI/igniteui-angular-samples/issues/1954
<br />
<br />
<br />

docs(circular progress bar): update circular progress documentation

---

en/components/input_group.md
en/components/input_group_reactive_forms.md

Linked Issues: IgniteUI/igniteui-angular-samples/issues/1952
<br />
<br />
<br />

docs(input-group): improve input group & reactive forms documentation

---

en/components/combo_features.md

Closes #1924
<br />
<br />
<br />

Add auto focus search input section

---

en/components/icon.md

Linked Issues: IgniteUI/igniteui-angular-samples/issues/1953
<br />
<br />
<br />

docs(icon): refactor icon documentation

---

en/components/date_time_editor.md
en/components/dock-manager.md
en/components/toc.yml

Closes # 
<br />
<br />
<br />

docs(dock-manager): Add topic for Dock Manager

---

en/components/general/ignite-ui-licensing.md
en/components/toc.yml

Related to #1946
<br />
<br />
<br />

Add licensing topic

---

en/components/splitter.md
kr/components/splitter.md

Closes # 
<br />
<br />
<br />

fixing splitter topic to show samples

---

en/components/dock-manager.md

Closes # 
<br />
<br />
<br />

fix(dock-manager-topic): change demo url

---

en/components/dock-manager.md

Closes #1953 
<br />
<br />
<br />

Update import in code snippet

---

en/components/grid/grid.md

Closes # 
<br />
<br />
<br />

chore(*): CI trigger

---

en/components/general/framework-and-features/data-analysis.md
en/components/toc.yml
jp/components/general/framework-and-features/data-analysis.md

Closes #1957
<br />
<br />
<br />

Final changes

---

en/components/general/framework-and-features/data-analysis.md
en/components/general/ignite-ui-licensing.md
en/images/general/fullscreen-black-18dp.svg
en/images/general/fullscreen-white-18dp.svg

Closes # 
<br />
<br />
<br />

Update both data analysis and licensing topic

---

en/components/general/framework-and-features/data-analysis.md
jp/components/general/framework-and-features/data-analysis.md

Add no theming class to DA topic samples

---

web.config

Closes # 
<br />
<br />
<br />

Add shp and dbf fileExtensions

---

en/components/general/framework-and-features/data-analysis.md

Closes # 
<br />
<br />
<br />

chore(*): add package description

---

en/components/general/framework-and-features/data-analysis.md

Closes # 
<br />
<br />
<br />

Data analysis update master

---

en/components/general/framework-and-features/data-analysis.md

Closes # 
<br />
<br />
<br />

chore(*): Minor addition

---

en/components/general/framework-and-features/data-analysis.md

Closes # 
<br />
<br />
<br />

chore(*): minor changes

---

en/components/general/ignite-ui-licensing.md

Related https://github.com/IgniteUI/igniteui-angular/issues/7470
<br />
<br />
<br />

docs: upgrade command packages update, yarn note, token setup typo

---

en/components/grid/master_detail.md

Closes #1896 
jp doc has the correct api link

fix(mdv): fixing an api link #1896

---

en/components/drag_drop.md

Closes #1614
JP ver is correct, only en version needs this fix

fix(dd): fixing 3 api links #1614

---

en/components/grids_templates/multi_row_layout.md

docs(nav): removing tab nav from mrl doc #1935

---

package-lock.json
package.json

Closes # 
<br />
<br />
<br />

Update to 2.7.0

---

en/components/dialog.md
en/components/general/framework-and-features/data-analysis.md
jp/components/dialog.md

Closes #2028
<br />
<br />
<br />

Update view in full size button - vNext

---

en/components/dialog.md
en/components/general/framework-and-features/data-analysis.md
jp/components/dialog.md

Closes #2028
<br />
<br />
<br />

Update view in full size button - master

---

package-lock.json
package.json

Closes # 
<br />
<br />
<br />

updating template dep to 2.7.1 so that DV TAAS button may be shown
